// Qualitative Analysis — Cation Tests
// All reactions written in full on answer side

const CH2_CARDS = [

  // ─── GROUP 1 ───
  { cat: "group-1", cl: "c-g1",
    f: "Group 1 cations + dil HCl → ?",
    fs: "Ag⁺, Pb²⁺, Hg₂²⁺",
    b: "AgCl↓ (white) + PbCl₂↓ (white) + Hg₂Cl₂↓ (white)",
    bs: "All three form white precipitates",
    n: "Group 1 = chloride-insoluble cations" },

  // ─── GROUP 2A ───
  { cat: "group-2A", cl: "c-g2a",
    f: "Group 2A cations + H₂S (dil HCl) → ?",
    fs: "Pb²⁺, Cu²⁺, Bi³⁺, Hg²⁺, Cd²⁺",
    b: "PbS↓ (black) + CuS↓ (black) + Bi₂S₃↓ (black) + HgS↓ (black) + CdS↓ (yellow)",
    bs: "All black except CdS which is yellow",
    n: "Group 2A = acid-insoluble sulphides" },

  // ─── GROUP 2B ───
  { cat: "group-2B", cl: "c-g2b",
    f: "Group 2B cations + H₂S (dil HCl) → ?",
    fs: "As³⁺, Sn²⁺, Sn⁴⁺, Sb³⁺",
    b: "As₂S₃↓ (yellow) + SnS₂↓ (yellow) + SnS↓ (brown) + Sb₂S₃↓ (orange)",
    bs: "All colored sulphides",
    n: "To distinguish 2A vs 2B: 2A insoluble in YAS ((NH₄)₂S), 2B soluble in YAS" },

  // ─── GROUP 3 ───
  { cat: "group-3", cl: "c-g3",
    f: "Group 3 cations + NH₄OH + NH₄Cl → ?",
    fs: "Al³⁺, Cr³⁺, Fe³⁺",
    b: "Al(OH)₃↓ (gelatinous white) + Cr(OH)₃↓ (dirty green) + Fe(OH)₃↓ (reddish brown)",
    bs: "All form hydroxide precipitates with distinct colors",
    n: "NH₄Cl prevents Mg²⁺ precipitation in this group" },

  // ─── GROUP 4 ───
  { cat: "group-4", cl: "c-g4",
    f: "Group 4 cations + H₂S + NH₄OH + NH₄Cl → ?",
    fs: "Zn²⁺, Ni²⁺, Co²⁺, Mn²⁺",
    b: "ZnS↓ (dirty white) + NiS↓ (black) + CoS↓ (black) + MnS↓ (light pink)",
    bs: "All form sulphide precipitates",
    n: "Basic medium (NH₄OH) — base-soluble sulphides" },

  // ─── GROUP 5 ───
  { cat: "group-5", cl: "c-g5",
    f: "Group 5 cations + (NH₄)₂CO₃ + NH₄OH → ?",
    fs: "Ba²⁺, Sr²⁺, Ca²⁺",
    b: "BaCO₃↓ (white) + SrCO₃↓ (white) + CaCO₃↓ (white)",
    bs: "All white carbonate precipitates",
    n: "Alkaline earth carbonates" },

  // ─── GROUP 6 ───
  { cat: "group-6", cl: "c-g6",
    f: "Group 6 cation + Na₂HPO₄ + NH₄OH → ?",
    fs: "Mg²⁺",
    b: "Mg(NH₄)PO₄↓ (white)",
    bs: "White crystalline precipitate",
    n: "Soluble group — only Mg²⁺ precipitates with phosphate" },

  // ─── GROUP 7 — NH₄⁺ ───
  { cat: "group-7", cl: "c-g7",
    f: "NH₄⁺ salt + aq. NaOH/Ca(OH)₂ → ?",
    fs: "Ammonium ion test",
    b: "NH₃↑ (gas)",
    bs: "Smell detected, turns red litmus blue, forms white dense fumes with HCl (NH₄Cl)",
    n: "NH₃ + HCl → NH₄Cl white fumes" },

  // ─── ORIGINAL SOLUTION TESTS ───
  { cat: "original-soln", cl: "c-orig",
    f: "Salt + dil HCl / conc HCl / dil HNO₃ / conc HNO₃ / aqua regia → ?",
    fs: "Original solution test",
    b: "O.S (original solution formed)",
    bs: "Use appropriate acid to dissolve salt",
    n: "Choice depends on reactivity and solubility of salt" },

  // ─── ZERO GROUP (AMMONIUM) ───
  { cat: "zero-group", cl: "c-zero",
    f: "Ammonium salt + aq. NaOH → ?",
    fs: "Rxn with NaOH/Ca(OH)₂",
    b: "NH₃↑",
    bs: "Detected by smell, red litmus → blue, glass rod dipped in HCl → white fumes (NH₄Cl)",
    n: "NH₃ + HCl → NH₄Cl" },

  // ─── Mn²⁺ TESTS ───
  { cat: "mn-tests", cl: "c-mn",
    f: "Mn²⁺ + H₂O₂ + NaOH(aq) → ?",
    fs: "Test for Mn²⁺",
    b: "MnO₂·H₂O↓ (hydrated manganese IV oxide — brown-black ppt)",
    bs: "",
    n: "" },

  { cat: "mn-tests", cl: "c-mn",
    f: "CuSO₄ + 4NH₃ → ?",
    fs: "Ammonia passed through blue CuSO₄",
    b: "[Cu(NH₃)₄]SO₄ (deep blue — dye, famous square-planar)",
    bs: "",
    n: "" },

  { cat: "nessler", cl: "c-nessler",
    f: "Ammonium salt (NH₄⁺) + KOH + K₂HgI₄ → ?",
    fs: "Nessler's reagent test",
    b: "HgO·Hg(NH₂)I (iodide of Millon's base — brown ppt)",
    bs: "",
    n: "" },

  { cat: "cobalt-nitrite", cl: "c-co",
    f: "3NH₄⁺ + Na₃[Co(NO₂)₆] → ?",
    fs: "Sodium cobaltinitrite test",
    b: "(NH₄)₃[Co(NO₂)₆]↓ (yellow ppt)",
    bs: "",
    n: "" },

  { cat: "hexachloroplatinic", cl: "c-pt",
    f: "3NH₄⁺ + H₂PtCl₆ → ?",
    fs: "Hexachloroplatinic acid",
    b: "(NH₄)₂[PtCl₆]↓ (yellow ppt)",
    bs: "",
    n: "" },

  { cat: "p-nitrobenzene", cl: "c-organic",
    f: "p-Nitrobenzene diazonium chloride + NH₄⁺ + OH⁻ → ?",
    fs: "Organic reagent test for NH₄⁺",
    b: "O₂N—⟨benzene ring⟩—N=N—NH₂ + Cl⁻ + H₂O (red solution)",
    bs: "",
    n: "" },

  // ─── GROUP 2 — Pb²⁺ TESTS ───
  { cat: "pb-tests", cl: "c-pb",
    f: "Pb²⁺ + HCl → ?",
    fs: "Lead chloride test",
    b: "PbCl₂↓ (white ppt, insoluble in cold water, soluble in hot water)",
    bs: "Conc HCl or KCl(aq) → [PbCl₄]²⁻ (soluble)",
    n: "" },

  { cat: "pb-tests", cl: "c-pb",
    f: "Pb²⁺ + H₂S → PbS (black) → ?",
    fs: "Via PbS intermediate",
    b: "PbS + dil HNO₃ → Pb²⁺ + S↓ + NO↑ → (conc HNO₃ + boil) → PbSO₄↓",
    bs: "",
    n: "" },

  { cat: "pb-tests", cl: "c-pb",
    f: "Pb²⁺ + aq. NH₃ → ?",
    fs: "Ammonia test",
    b: "Pb(OH)₂↓ (white) — excess NH₃ → no dissolution",
    bs: "",
    n: "" },

  { cat: "pb-tests", cl: "c-pb",
    f: "Pb²⁺ + aq. NaOH → ?",
    fs: "Sodium hydroxide test",
    b: "Pb(OH)₂↓ (white) — excess NaOH → Na₂[Pb(OH)₄] (soluble) → (heat) → PbO₂↓ (black) or S₂O₈²⁻",
    bs: "",
    n: "" },

  { cat: "pb-tests", cl: "c-pb",
    f: "Pb²⁺ + SO₄²⁻ → ?",
    fs: "Sulphate test",
    b: "PbSO₄↓ (white) — (conc H₂SO₄) → Pb(HSO₄)₂ (soluble, excess ammonium acetate CH₃COONH₄) → [Pb(CH₃COO)₂]⁻ (soluble)",
    bs: "",
    n: "" },

  { cat: "pb-tests", cl: "c-pb",
    f: "Pb²⁺ + CrO₄²⁻ → ?",
    fs: "Chromate test",
    b: "PbCrO₄↓ (yellow ppt) — (acid) → Pb²⁺ + Cr₂O₇²⁻ (orange-red solution) — (base) → [Pb(OH)₄]²⁻ + CrO₄²⁻ (yellow)",
    bs: "",
    n: "" },

  { cat: "pb-tests", cl: "c-pb",
    f: "Pb²⁺ + KI → ?",
    fs: "Iodide test",
    b: "PbI₂↓ (yellow) — (excess conc KI) → [PbI₄]²⁻ (soluble)",
    bs: "",
    n: "" },

  { cat: "pb-tests", cl: "c-pb",
    f: "Pb²⁺ + PO₄³⁻ → ?",
    fs: "Phosphate test",
    b: "Pb₃(PO₄)₂ (yellow)",
    bs: "",
    n: "" },

  { cat: "pb-tests", cl: "c-pb",
    f: "Pb²⁺ + 2CN⁻ → ?",
    fs: "Cyanide test",
    b: "Pb(CN)₂ (white) — (excess KCN) → no dissolution",
    bs: "",
    n: "" },

  // ─── Ag⁺ TESTS ───
  { cat: "ag-tests", cl: "c-ag",
    f: "Ag⁺ + HCl → ?",
    fs: "Silver chloride test",
    b: "AgCl↓ (white) — (conc HCl or conc KCl) → [AgCl₂]⁻ (soluble)",
    bs: "",
    n: "Dissolution table: dil NH₃ ✓, conc NH₃ ✓, aq. KOH ✓, aq. (Na₂S₂O₃) ✓, hypo ✓" },

  { cat: "ag-tests", cl: "c-ag",
    f: "Ag⁺ + H₂S → Ag₂S (black) → ?",
    fs: "Via sulphide",
    b: "Ag₂S — (conc HNO₃ + Δ) → Ag⁺ + S↓ + NO↑",
    bs: "",
    n: "" },

  { cat: "ag-tests", cl: "c-ag",
    f: "Ag⁺ + aq. NH₃ → ?",
    fs: "Ammonia test",
    b: "Ag₂O↓ (brown ppt) — (excess NH₃) → [Ag(NH₃)₂]⁺ (soluble)",
    bs: "",
    n: "" },

  { cat: "ag-tests", cl: "c-ag",
    f: "Ag⁺ + aq. NaOH → ?",
    fs: "Sodium hydroxide test",
    b: "Ag₂O↓ (brown ppt) — (excess NaOH) → no dissolution",
    bs: "",
    n: "" },

  { cat: "ag-tests", cl: "c-ag",
    f: "Ag⁺ + KI → ?",
    fs: "Iodide test",
    b: "AgI (yellow)",
    bs: "",
    n: "" },

  { cat: "ag-tests", cl: "c-ag",
    f: "Ag⁺ + CrO₄²⁻ → ?",
    fs: "Chromate test",
    b: "Ag₂CrO₄↓ (brick red ppt) — (aq. NH₃) → [Ag(NH₃)₂]⁺ + CrO₄²⁻",
    bs: "",
    n: "" },

  { cat: "ag-tests", cl: "c-ag",
    f: "Ag⁺ + KCN → ?",
    fs: "Cyanide test",
    b: "AgCN (white) — (excess KCN) → [Ag(CN)₂]⁻ (soluble)",
    bs: "",
    n: "" },

  { cat: "ag-tests", cl: "c-ag",
    f: "Ag⁺ + PO₄³⁻ → ?",
    fs: "Phosphate test",
    b: "Ag₃PO₄ (yellow)",
    bs: "",
    n: "" },

  { cat: "ag-tests", cl: "c-ag",
    f: "Ag⁺ + AsO₄³⁻ → ?",
    fs: "Arsenate test",
    b: "Ag₃AsO₄ (brownish red)",
    bs: "",
    n: "" },

  { cat: "ag-tests", cl: "c-ag",
    f: "Ag⁺ + CO₃²⁻ → Ag₂CO₃ → ?",
    fs: "Carbonate test (boiled)",
    b: "Ag₂CO₃ (boiled) → Ag₂O (brown)",
    bs: "",
    n: "" },

  { cat: "ag-tests", cl: "c-ag",
    f: "Ag⁺ + K₄[Fe(CN)₆] → ?",
    fs: "Ferrocyanide test",
    b: "Ag₄[Fe(CN)₆]↓ (white ppt)",
    bs: "",
    n: "" },

  // ─── Hg₂²⁺ TESTS (Hg₂²⁺ never exists as Hg⁺ — 2Hg⁺ is diamagnetic) ───
  { cat: "hg2-tests", cl: "c-hg2",
    f: "Hg₂²⁺ + HCl → ?",
    fs: "Mercurous chloride (Hg₂²⁺ exists as dimer)",
    b: "Hg₂Cl₂ (white ppt) — (aq. NH₃, disproportionation) → Hg (black) + Hg(NH₂)Cl (white) — overall black",
    bs: "Aqua regia (HCl + HNO₃, 3:1) → HgCl₂ + NO↑",
    n: "" },

  { cat: "hg2-tests", cl: "c-hg2",
    f: "Hg₂²⁺ + H₂S → ?",
    fs: "Mercurous sulphide",
    b: "HgS (black) + Hg (black) — overall black, then via aqua regia (HgCl₂) → [Hg₂S]²⁻ (polysulphides)",
    bs: "",
    n: "" },

  { cat: "hg2-tests", cl: "c-hg2",
    f: "Hg₂(NO₃)₂ + aq. NH₃ → ?",
    fs: "Ammonia test",
    b: "Hg↓ (black) + HgO·Hg(NH₂)NO₃ (white) — overall black",
    bs: "",
    n: "" },

  { cat: "hg2-tests", cl: "c-hg2",
    f: "Hg₂²⁺ + aq. NaOH → ?",
    fs: "Sodium hydroxide test",
    b: "Hg₂O↓ (black) + H₂O — (boil) → HgO (yellow) + Hg",
    bs: "",
    n: "" },

  { cat: "hg2-tests", cl: "c-hg2",
    f: "Hg₂²⁺ + CrO₄²⁻ → ?",
    fs: "Chromate test",
    b: "Hg₂CrO₄ (red ppt)",
    bs: "",
    n: "" },

  { cat: "hg2-tests", cl: "c-hg2",
    f: "Hg₂²⁺ + KI → ?",
    fs: "Iodide test",
    b: "Hg₂I₂ (green ppt) — (boil) → Hg (black) + HgI₂ (red, scarlet)",
    bs: "",
    n: "" },

  { cat: "hg2-tests", cl: "c-hg2",
    f: "Hg₂²⁺ + KI (excess) → ?",
    fs: "Excess iodide",
    b: "[HgI₄]²⁻ + Hg",
    bs: "",
    n: "" },

  // ─── Hg²⁺ TESTS ───
  { cat: "hg-tests", cl: "c-hg",
    f: "Hg²⁺ + KSCN → ?",
    fs: "Thiocyanate test",
    b: "Hg + Hg(CNS)₂ (grey/black)",
    bs: "",
    n: "" },

  { cat: "hg-tests", cl: "c-hg",
    f: "Hg₂²⁺ + SnCl₂ → ?",
    fs: "Stannous chloride test",
    b: "Hg↓ + Sn⁴⁺",
    bs: "",
    n: "" },

  { cat: "hg-tests", cl: "c-hg",
    f: "Hg₂²⁺ + Cu/Al → ?",
    fs: "Displacement with metals",
    b: "Hg↓ + Cu²⁺/Al³⁺",
    bs: "",
    n: "" },

];
