window.LABELS = {
  'group-overview': 'Group Overview',
  'nh4-tests':      'NH₄⁺ Tests',
  'pb-rxns':        'Pb²⁺ Rxns',
  'ag-rxns':        'Ag⁺ Rxns',
  'hg2-rxns':       'Hg₂²⁺ Rxns'
};

window.CARDS = [
  // ── GROUP OVERVIEW ──
  { cat:"group-overview", cl:"c-qa-grp1",
    f:"Qual Analysis: Group 1 cations + Group reagent → ?",
    fs:"Ag⁺, Pb²⁺, Hg₂²⁺",
    b:"dil HCl(aq) → AgCl↓, PbCl₂, Hg₂Cl₂ — all White ppt", bs:"", n:"" },
  { cat:"group-overview", cl:"c-qa-grp2a",
    f:"Qual Analysis: Group 2A cations + Group reagent → ?",
    fs:"Pb²⁺, Cu²⁺, Bi³⁺, Hg²⁺, Cd²⁺",
    b:"H₂S(g) with dil HCl → PbS↓, CuS↓, Bi₂S₃↓, HgS↓ (Black); CdS↓ (Yellow)", bs:"", n:"" },
  { cat:"group-overview", cl:"c-qa-grp2b",
    f:"Qual Analysis: Group 2B cations + Group reagent → ?",
    fs:"As³⁺, Sn²⁺, Sn⁴⁺, Sb³⁺",
    b:"H₂S with dil HCl → As₂S₃↓, SnS₂↓ (Yellow); SnS↓ (Brown); Sb₂S₃↓ (Orange)", bs:"",
    n:"2A insoluble in YAS. 2B soluble in YAS. YAS = (NH₄)₂Sₓ (poly sulphide, x=2,3,5)" },
  { cat:"group-overview", cl:"c-qa-grp3",
    f:"Qual Analysis: Group 3 cations + Group reagent → ?",
    fs:"Al³⁺, Cr³⁺, Fe³⁺",
    b:"NH₄OH + NH₄Cl → Al(OH)₃↓ (gelatinous white); Cr(OH)₃↓ (dirty green); Fe(OH)₃↓ (reddish brown)", bs:"", n:"" },
  { cat:"group-overview", cl:"c-qa-grp4",
    f:"Qual Analysis: Group 4 cations + Group reagent → ?",
    fs:"Zn²⁺, Ni²⁺, Co²⁺, Mn²⁺",
    b:"H₂S with NH₄OH + NH₄Cl → ZnS↓ (dirty white); NiS↓, CoS↓ (Black); MnS↓ (light pink)", bs:"", n:"" },
  { cat:"group-overview", cl:"c-qa-grp5",
    f:"Qual Analysis: Group 5 cations + Group reagent → ?",
    fs:"Ba²⁺, Sr²⁺, Ca²⁺",
    b:"(NH₄)₂CO₃ + NH₄OH → BaCO₃↓, SrCO₃↓, CaCO₃↓ — all White ppt", bs:"", n:"" },
  { cat:"group-overview", cl:"c-qa-grp6",
    f:"Qual Analysis: Group 6 cation + Group reagent → ?",
    fs:"Mg²⁺",
    b:"Na₂HPO₄ + NH₄OH → Mg(NH₄)PO₃↓ White", bs:"", n:"" },
  { cat:"group-overview", cl:"c-qa-grp7",
    f:"Qual Analysis: Group 7 cation + Group reagent → ?",
    fs:"NH₄⁺",
    b:"aq. NaOH / Ca(OH)₂ → NH₃↑", bs:"", n:"" },

  // ── NH₄⁺ TESTS ──
  { cat:"nh4-tests", cl:"c-qa-nh4",
    f:"NH₄⁺ + aq NaOH → ? Detection tests?",
    fs:"Ammonium salt in base",
    b:"NH₃↑ (pungent smell) — turns red litmus blue; glass rod dipped in HCl shows white dense fumes (NH₄Cl)",
    bs:"NH₃ + HCl → NH₄Cl", n:"" },
  { cat:"nh4-tests", cl:"c-qa-nh4",
    f:"Mn²⁺ + H₂O₂ + NH₃(aq) → ? (NH₃ detection test ii)",
    fs:"",
    b:"MnO₂ (hydrated) + NH₄⁺ — Brown-black ppt", bs:"Hydrated manganese(IV) oxide", n:"" },
  { cat:"nh4-tests", cl:"c-qa-nh4",
    f:"CuSO₄ + 4NH₃ → ? (NH₃ detection — blue CuSO₄ turns deep blue)",
    fs:"Ammonia passed through CuSO₄ solution",
    b:"[Cu(NH₃)₄]SO₄ — deep blue; dsp² paramagnetic, square planar", bs:"", n:"" },
  { cat:"nh4-tests", cl:"c-qa-nh4",
    f:"Nessler's Reagent test for NH₄⁺ → ?",
    fs:"KOH + K₂HgI₄",
    b:"NH₄⁺ + KOH + K₂HgI₄ → HgO·Hg(NH₂)I — Iodide of Millon's base — Brown ppt", bs:"", n:"" },
  { cat:"nh4-tests", cl:"c-qa-nh4",
    f:"3NH₄⁺ + Na₃[Co(NO₂)₆] → ? (NH₄⁺ test v)",
    fs:"Sodium hexanitrocobaltate(III)",
    b:"(NH₄)₃[Co(NO₂)₆]↓ — yellow ppt", bs:"", n:"" },
  { cat:"nh4-tests", cl:"c-qa-nh4",
    f:"3NH₄⁺ + H₂PtCl₆ → ? (hexachloroplatinic acid)",
    fs:"",
    b:"(NH₄)₂[PtCl₆]↓ — yellow ppt", bs:"", n:"" },
  { cat:"nh4-tests", cl:"c-qa-nh4",
    f:"p-nitrobenzene diazonium chloride + NH₄⁺ + OH⁻ → ?",
    fs:"NH₄⁺ diazonium coupling test",
    b:"O₂N-C₆H₄-N=N-NH₂ + Cl⁻ + H₂O — Red solution", bs:"", n:"" },

  // ── Pb²⁺ REACTIONS ──
  { cat:"pb-rxns", cl:"c-qa-pb",
    f:"Pb²⁺ + HCl → ? then conc HCl/KCl → ?",
    fs:"",
    b:"PbCl₂↓ (white; insol cold, sol hot water) → excess conc HCl/KCl: [PbCl₄]²⁻(aq)", bs:"", n:"" },
  { cat:"pb-rxns", cl:"c-qa-pb",
    f:"Pb²⁺ + H₂S → ? then conc HNO₃ → ? then conc HNO₃ + boil → ?",
    fs:"",
    b:"PbS↓ (black) → conc HNO₃: Pb²⁺ + S↓ (NOT H₂S) → conc HNO₃ + boil: PbSO₄↓", bs:"", n:"" },
  { cat:"pb-rxns", cl:"c-qa-pb",
    f:"Pb²⁺ + aq NH₃ → ? excess NH₃ → ?",
    fs:"",
    b:"Pb(OH)₂↓ (white) → excess NH₃: No dissolution", bs:"", n:"" },
  { cat:"pb-rxns", cl:"c-qa-pb",
    f:"Pb²⁺ + aq NaOH → ? excess NaOH → ? then H₂O₂/Δ or S₂O₈²⁻ → ?",
    fs:"",
    b:"Pb(OH)₂↓ → excess NaOH: Na₂[Pb(OH)₄] → H₂O₂/Δ: PbO₂ (black)", bs:"", n:"" },
  { cat:"pb-rxns", cl:"c-qa-pb",
    f:"Pb²⁺ + SO₄²⁻ → ? then conc H₂SO₄ → ? then excess ammonium acetate → ?",
    fs:"",
    b:"PbSO₄↓ → conc H₂SO₄: Pb(HSO₄)₂ → excess CH₃COONH₄: [Pb(CH₃COO)₄]²⁻", bs:"", n:"" },
  { cat:"pb-rxns", cl:"c-qa-pb",
    f:"Pb²⁺ + CrO₄²⁻ → ? Acid → ? Base → ?",
    fs:"",
    b:"PbCrO₄↓ (yellow) → Acid: Pb²⁺ + Cr₂O₇²⁻ (orange-red) → Base: [Pb(OH)₄]²⁻ + CrO₄²⁻ (yellow)", bs:"", n:"" },
  { cat:"pb-rxns", cl:"c-qa-pb",
    f:"Pb²⁺ + KI → ? excess conc KI → ?",
    fs:"",
    b:"PbI₂↓ (yellow) → excess conc KI: [PbI₄]²⁻", bs:"", n:"" },
  { cat:"pb-rxns", cl:"c-qa-pb",
    f:"Pb²⁺ + PO₄³⁻ → ?",
    fs:"", b:"Pb₃(PO₄)₂↓", bs:"", n:"" },
  { cat:"pb-rxns", cl:"c-qa-pb",
    f:"Pb²⁺ + 2CN⁻ → ? excess KCN → ?",
    fs:"",
    b:"Pb(CN)₂↓ (white) → excess KCN: No dissolution", bs:"", n:"" },

  // ── Ag⁺ REACTIONS ──
  { cat:"ag-rxns", cl:"c-qa-ag",
    f:"Ag⁺ + HCl → ? excess conc HCl/KCl → ?",
    fs:"",
    b:"AgCl↓ (white) → [AgCl₂]⁻", bs:"", n:"" },
  { cat:"ag-rxns", cl:"c-qa-ag",
    f:"AgCl / AgBr / AgI — dissolution with dil NH₃ / conc NH₃ / aq KOH / aq Na₂S₂O₃?",
    fs:"",
    b:"AgCl: ✓dil NH₃, ✓conc NH₃, ✓KOH, ✓hypo | AgBr: ✗dil NH₃, ✓conc NH₃, ✓KOH, ✓hypo | AgI: ✗, ✗, ✓KOH, ✓hypo",
    bs:"Hypo = Na₂S₂O₃", n:"" },
  { cat:"ag-rxns", cl:"c-qa-ag",
    f:"Ag⁺ + H₂S → ? then conc HNO₃ + Δ → ?",
    fs:"",
    b:"Ag₂S↓ → conc HNO₃ + Δ: Ag⁺ + S↓ (NOT gas)", bs:"", n:"" },
  { cat:"ag-rxns", cl:"c-qa-ag",
    f:"Ag⁺ + aq NH₃ → ? excess NH₃ → ?",
    fs:"",
    b:"Ag₂O↓ (brown ppt) → excess NH₃: [Ag(NH₃)₂]⁺", bs:"", n:"" },
  { cat:"ag-rxns", cl:"c-qa-ag",
    f:"Ag⁺ + aq NaOH → ? excess NaOH → ?",
    fs:"",
    b:"Ag₂O↓ → excess NaOH: No dissolution", bs:"", n:"" },
  { cat:"ag-rxns", cl:"c-qa-ag",
    f:"Ag⁺ + KI → ?",
    fs:"", b:"AgI↓ (yellow)", bs:"", n:"" },
  { cat:"ag-rxns", cl:"c-qa-ag",
    f:"Ag⁺ + CrO₄²⁻ → ? then aq NH₃ → ?",
    fs:"",
    b:"Ag₂CrO₄↓ (brick red ppt) → aq NH₃: [Ag(NH₃)₂]⁺", bs:"", n:"" },
  { cat:"ag-rxns", cl:"c-qa-ag",
    f:"Ag⁺ + KCN → ? excess KCN → ?",
    fs:"",
    b:"AgCN↓ (white) → excess KCN: [Ag(CN)₂]⁻", bs:"", n:"" },
  { cat:"ag-rxns", cl:"c-qa-ag",
    f:"Ag⁺ + PO₄³⁻ → ?",
    fs:"", b:"Ag₃PO₄↓ (yellow)", bs:"", n:"" },
  { cat:"ag-rxns", cl:"c-qa-ag",
    f:"Ag⁺ + AsO₄³⁻ → ?",
    fs:"", b:"Ag₃AsO₄↓ (brownish red)", bs:"", n:"" },
  { cat:"ag-rxns", cl:"c-qa-ag",
    f:"Ag⁺ + CO₃²⁻ → ? then boiled → ?",
    fs:"",
    b:"Ag₂CO₃↓ → boiled: Ag₂O (brown)", bs:"", n:"" },
  { cat:"ag-rxns", cl:"c-qa-ag",
    f:"Ag⁺ + K₄[Fe(CN)₆] → ?",
    fs:"", b:"Ag₄[Fe(CN)₆]↓ (white ppt)", bs:"", n:"" },

  // ── Hg₂²⁺ REACTIONS ──
  { cat:"hg2-rxns", cl:"c-qa-hg2",
    f:"Key fact: does Hg₂²⁺ exist as Hg⁺?",
    fs:"",
    b:"NO — Hg₂²⁺ is diamagnetic (paired electrons in Hg–Hg bond). Never Hg⁺.", bs:"", n:"" },
  { cat:"hg2-rxns", cl:"c-qa-hg2",
    f:"Hg₂²⁺ + HCl → ? then aq NH₃ → ? (disproportionation) then aqua regia → ?",
    fs:"",
    b:"Hg₂Cl₂↓ (white) → NH₃: Hg↓(black) + Hg(NH₂)Cl(white) → overall black | Aqua regia: HgCl₂ + NO↑",
    bs:"", n:"" },
  { cat:"hg2-rxns", cl:"c-qa-hg2",
    f:"Hg₂²⁺ + H₂S → ?",
    fs:"",
    b:"HgS↓ (black) + Hg↓ (black) → aqua regia → HgCl₂ → + S²⁻: [HgSₓ]²⁻ (poly sulphides)",
    bs:"", n:"" },
  { cat:"hg2-rxns", cl:"c-qa-hg2",
    f:"Hg₂(NO₃)₂ + aq NH₃ → ?",
    fs:"",
    b:"Hg↓ (black) + HgOHg(NH₂)NO₃ (white) — overall black ppt", bs:"", n:"" },
  { cat:"hg2-rxns", cl:"c-qa-hg2",
    f:"Hg₂²⁺ + aq NaOH → ? then boil → ?",
    fs:"",
    b:"Hg₂O↓ (black) + H₂O → boil: HgO (yellow) + Hg↓", bs:"", n:"" },
  { cat:"hg2-rxns", cl:"c-qa-hg2",
    f:"Hg₂²⁺ + CrO₄²⁻ → ?",
    fs:"", b:"Hg₂CrO₄↓ (red ppt)", bs:"", n:"" },
  { cat:"hg2-rxns", cl:"c-qa-hg2",
    f:"Hg₂²⁺ + KI → ? boil → ? excess KI → ?",
    fs:"",
    b:"Hg₂I₂↓ (green ppt) → boil: Hg↓ + HgI₂ (red/scarlet) → excess KI: [HgI₄]²⁻ + Hg",
    bs:"", n:"Green ppt (★) and red/scarlet HgI₂ (★) are important" },
  { cat:"hg2-rxns", cl:"c-qa-hg2",
    f:"Hg₂²⁺ + KCN → ?",
    fs:"", b:"Hg↓ + Hg(CN)₂ — grey/black ppt", bs:"", n:"" },
  { cat:"hg2-rxns", cl:"c-qa-hg2",
    f:"Hg₂²⁺ + SnCl₂ → ?",
    fs:"", b:"Hg↓(l) + Sn⁴⁺", bs:"", n:"" },
  { cat:"hg2-rxns", cl:"c-qa-hg2",
    f:"Hg₂²⁺ + Cu/Al → ?",
    fs:"", b:"Hg↓(l) + Cu²⁺/Al³⁺", bs:"", n:"" },
];
