window.LABELS = {
  'disproportionation':'Disprop',
  'hydrolysis-halogens':'Halogens',
  'hydrolysis-noble':'Noble gases',
  'hydrolysis-oxyhalides':'Oxy halides',
  'hydrolysis-S/Se/Te':'S/Se/Te',
  'hydrolysis-N/P':'N/P group',
  'hydrolysis-C/Si':'C/Si group',
  'hydrolysis-boron':'Boron',
  'metal-oxides':'Metal oxides',
  'heating-carbonates':'Carbonates',
  'heating-nitrates':'Nitrates',
  'heating-sulphates':'Sulphates',
  'heating-oxalates':'Oxalates',
  'heating-oxides':'Oxide decomp',
  'heating-NH4':'NH₄ salts',
  'heating-azides':'Azides',
  'heating-acids':'Acid heating',
  'heating-salts':'Salt heating',
  'internal-hydrolysis':'Internal hydrolysis',
  'redox':'Redox agents',
  'misc':'Amphoteric',
  'dehydration':'Conc H₂SO₄',
  'acid-strength':'Acid strength'
};

window.CARDS = [
  // ── DISPROPORTIONATION ──
  { cat:"disproportionation", cl:"c-disp",
    f:"X₂ + OH⁻ → ? (X = Cl, Br, I — basic medium)", fs:"Halogens in alkali",
    b:"X⁻ + XO₃⁻", bs:"0 → -1 and +5",
    n:"F₂ does NOT disproportionate — no d-orbitals, most electronegative" },
  { cat:"disproportionation", cl:"c-disp",
    f:"Br₂ + NaOH/KOH (hot conc.) → ?", fs:"",
    b:"Br⁻ + BrO₃⁻ (bromate ion)", bs:"",
    n:"Hot conc → XO₃⁻. Cold dilute → X⁻ + XO⁻ (hypohalite). Same rxn in acidic medium = comproportionation." },
  { cat:"disproportionation", cl:"c-disp",
    f:"P₄ (white) + NaOH/KOH/Ca(OH)₂ + H₂O → ?", fs:"",
    b:"PH₃↑ (phosphene) + H₂PO₂⁻ (hypophosphite)", bs:"P: 0 → -3 and +1",
    n:"Only white phosphorus does this. Red/black do not." },
  { cat:"disproportionation", cl:"c-disp",
    f:"S + OH⁻ → ? (heat)", fs:"Sulphur in base",
    b:"S²⁻ + S₂O₃²⁻ (thiosulphate)", bs:"S: 0 → -2 and +2", n:"" },
  { cat:"disproportionation", cl:"c-disp",
    f:"ClO₂ + H₂O → ?", fs:"Mixed oxide (Cl in +4)",
    b:"HClO₂ + HClO₃", bs:"+4 → +3 and +5",
    n:"NO₂ + H₂O → HNO₂ + HNO₃ (same pattern)" },
  { cat:"disproportionation", cl:"c-disp",
    f:"ClO₃ or Cl₂O₆ + KOH → ?", fs:"",
    b:"KClO₃ + KClO₄", bs:"", n:"" },

  // ── HYDROLYSIS — HALOGEN GROUP ──
  { cat:"hydrolysis-halogens", cl:"c-hydro",
    f:"ClF₃ + H₂O → ?", fs:"Interhalogen hydrolysis: small halogen = HF, large = oxyacid",
    b:"HF + HClO₂", bs:"",
    n:"Rule: hydrolysis of interhalogens → HF (small halogen) + oxyacid of larger halogen" },
  { cat:"hydrolysis-halogens", cl:"c-hydro",
    f:"BrF₅ + H₂O → ?", fs:"", b:"HF + HBrO₃", bs:"", n:"" },
  { cat:"hydrolysis-halogens", cl:"c-hydro",
    f:"I₂Cl₆ + H₂O → ?", fs:"", b:"HCl + HIO₂", bs:"I is +3 here", n:"" },
  { cat:"hydrolysis-halogens", cl:"c-hydro",
    f:"IF₅ + H₂O → ?", fs:"", b:"HF + HIO₃", bs:"I is +5", n:"" },
  { cat:"hydrolysis-halogens", cl:"c-hydro",
    f:"IF₇ + H₂O → ?", fs:"",
    b:"HF + HIO₄ → (+ 2H₂O) → H₅IO₆", bs:"H₅IO₆ is the final product (octahedral I)",
    n:"IF₇ is the only one giving H₅IO₆ via HIO₄ intermediate" },

  // ── HYDROLYSIS — NOBLE GASES ──
  { cat:"hydrolysis-noble", cl:"c-hydro",
    f:"XeF₂ + H₂O → ?", fs:"Noble gas fluoride hydrolysis",
    b:"Xe↑ + O₂↑ + HF", bs:"", n:"" },
  { cat:"hydrolysis-noble", cl:"c-hydro",
    f:"XeF₄ + H₂O → ?", fs:"",
    b:"XeO₃ + Xe + O₂ + HF", bs:"Disproportionation during hydrolysis", n:"" },
  { cat:"hydrolysis-noble", cl:"c-hydro",
    f:"XeF₆ + H₂O → ?", fs:"", b:"XeO₃ + HF", bs:"", n:"" },

  // ── HYDROLYSIS — OXY HALIDES ──
  { cat:"hydrolysis-oxyhalides", cl:"c-hydro",
    f:"SOCl₂ + H₂O → ?", fs:"Oxy halide hydrolysis", b:"H₂SO₃ + HCl", bs:"", n:"" },
  { cat:"hydrolysis-oxyhalides", cl:"c-hydro",
    f:"SO₂Cl₂ + HCl → ?", fs:"", b:"H₂SO₄ + HCl", bs:"", n:"" },
  { cat:"hydrolysis-oxyhalides", cl:"c-hydro",
    f:"POCl₃ + H₂O → ?", fs:"", b:"H₃PO₄ + HCl", bs:"", n:"" },
  { cat:"hydrolysis-oxyhalides", cl:"c-hydro",
    f:"NOCl + H₂O → ?", fs:"", b:"HNO₂ + HCl", bs:"", n:"" },
  { cat:"hydrolysis-oxyhalides", cl:"c-hydro",
    f:"(CrO₂Cl)₂ + H₂O → ?", fs:"Chromyl chloride", b:"H₂Cr₂O₇ + HCl", bs:"", n:"" },

  // ── HYDROLYSIS — S/Se/Te ──
  { cat:"hydrolysis-S/Se/Te", cl:"c-hydro",
    f:"S₂Cl₂ / S₂F₂ + H₂O → ?", fs:"Disulphur dihalide",
    b:"S↓ + SO₂ + HCl/HF", bs:"Disproportionation", n:"" },
  { cat:"hydrolysis-S/Se/Te", cl:"c-hydro",
    f:"SCl₂ / SF₂ + H₂O → ?", fs:"", b:"S↓ + SO₂↑ + HCl/HF", bs:"", n:"" },
  { cat:"hydrolysis-S/Se/Te", cl:"c-hydro",
    f:"SF₄ + H₂O → ?", fs:"", b:"SO₂ + HF", bs:"",
    n:"SF₆ is INERT to hydrolysis — 6 F atoms cause steric hindrance blocking attack" },
  { cat:"hydrolysis-S/Se/Te", cl:"c-hydro",
    f:"SeF₄ + H₂O → ?", fs:"", b:"SeO₂ + HF", bs:"", n:"" },
  { cat:"hydrolysis-S/Se/Te", cl:"c-hydro",
    f:"SeF₆ + H₂O → ?", fs:"",
    b:"H₂SeO₄ (selenic acid) via unstable H₆SeO₆", bs:"H₆SeO₆ − 2H₂O → H₂SeO₄",
    n:"SeF₆ does hydrolyse unlike SF₆ — Se is larger so less steric protection" },
  { cat:"hydrolysis-S/Se/Te", cl:"c-hydro",
    f:"TeF₆ + H₂O → ?", fs:"",
    b:"H₆TeO₆ (exists — stable due to large Te)", bs:"Telluric acid — octahedral Te",
    n:"Te is large enough to accommodate 6 OH groups — H₆TeO₆ is stable, unlike H₆SeO₆" },

  // ── HYDROLYSIS — N/P GROUP ──
  { cat:"hydrolysis-N/P", cl:"c-hydro",
    f:"NX₃ + H₂O → ? (X = Cl/Br/I)", fs:"Nitrogen trihalide",
    b:"NH₃ + HOX (hypohalous acid)", bs:"",
    n:"NF₃ undergoes negligible hydrolysis — almost non-polar (electronegativity difference ≈ 0)" },
  { cat:"hydrolysis-N/P", cl:"c-hydro",
    f:"PCl₃ + H₂O → ?", fs:"", b:"H₃PO₃ + HCl", bs:"P is +3", n:"" },
  { cat:"hydrolysis-N/P", cl:"c-hydro",
    f:"PCl₅ + excess H₂O → ?", fs:"", b:"H₃PO₄ + HCl", bs:"P is +5",
    n:"With small/moisture amount of water: PCl₅ + H₂O → POCl₃ + HCl (then + more H₂O → H₃PO₄)" },
  { cat:"hydrolysis-N/P", cl:"c-hydro",
    f:"AsCl₃ + H₂O → ?", fs:"", b:"H₃AsO₃ + HCl", bs:"As is +3, white ppt", n:"" },
  { cat:"hydrolysis-N/P", cl:"c-hydro",
    f:"SbCl₃ + H₂O → ?", fs:"Partial hydrolysis", b:"SbO⁺Cl⁻ + HCl", bs:"White ppt", n:"" },
  { cat:"hydrolysis-N/P", cl:"c-hydro",
    f:"BiCl₃ + H₂O → ?", fs:"Partial hydrolysis", b:"BiO⁺Cl⁻ + HCl", bs:"White ppt, turbid (1:1)", n:"" },

  // ── HYDROLYSIS — C/Si GROUP ──
  { cat:"hydrolysis-C/Si", cl:"c-hydro",
    f:"CF₄ / CCl₄ / CHCl₃ + H₂O → ?", fs:"Carbon tetrahalides",
    b:"No reaction", bs:"",
    n:"Absence of vacant p-orbital in valence shell — cannot be attacked by water" },
  { cat:"hydrolysis-C/Si", cl:"c-hydro",
    f:"CCl₄ + superheated steam → ?", fs:"H₂O(g), heat",
    b:"COCl₂ (phosgene) + HCl", bs:"Phosgene is a poisonous gas", n:"" },
  { cat:"hydrolysis-C/Si", cl:"c-hydro",
    f:"SiCl₄ + H₂O → ?", fs:"Easily hydrolysed — has vacant 3d orbital",
    b:"H₄SiO₄ + HCl → (−H₂O) → (H₂SiO₃)ₙ", bs:"Meta silicic acid — polymeric gel-like",
    n:"Si has vacant d-orbitals unlike C, so water can attack" },
  { cat:"hydrolysis-C/Si", cl:"c-hydro",
    f:"SiF₄ + 4H₂O → ?", fs:"Partial hydrolysis",
    b:"H₄SiO₄ + 4HF", bs:"Orthosilicic acid",
    n:"Instep: SiF₄ + 3H₂O → H₂SiO₃; 2SiF₄ + 4HF → 2H₂SiF₆; net: 3SiF₄ + 3H₂O → H₂SiO₃ + 2H₂SiF₆" },
  { cat:"hydrolysis-C/Si", cl:"c-hydro",
    f:"SnCl₄ + H₂O → ?", fs:"", b:"H₂SnO₃ + 4HCl", bs:"Meta stannic acid", n:"" },
  { cat:"hydrolysis-C/Si", cl:"c-hydro",
    f:"SnCl₂ + H₂O ⇌ ?", fs:"Incomplete hydrolysis", b:"Sn(OH)Cl + HCl", bs:"White ppt", n:"" },
  { cat:"hydrolysis-C/Si", cl:"c-hydro",
    f:"PbCl₄ + H₂O → ?", fs:"", b:"PbO₂ + HCl", bs:"",
    n:"PbCl₂ is insoluble — does not hydrolyse" },

  // ── HYDROLYSIS — BORON GROUP ──
  { cat:"hydrolysis-boron", cl:"c-hydro",
    f:"BX₃ + 3H₂O → ? (X = Cl/Br/I)", fs:"Boron trihalide — complete hydrolysis",
    b:"H₃BO₃ + 3HX", bs:"B(OH)₃",
    n:"BBCl₃ does NOT exist — 4 Cl atoms cause steric hindrance around small B" },
  { cat:"hydrolysis-boron", cl:"c-hydro",
    f:"BF₃ + 3H₂O → ? then what?", fs:"Partial hydrolysis",
    b:"H₃BO₃ + 3HF; then 3BF₃ + 3HF → 3HBF₄", bs:"Net: 4BF₃ + 3H₂O → H₃BO₃ + 3HBF₄ (1:3 ratio)",
    n:"BF₃ + KF → K⁺BF₄⁻" },
  { cat:"hydrolysis-boron", cl:"c-hydro",
    f:"AlCl₃ + H₂O → ?", fs:"", b:"Al(OH)₃ + HCl", bs:"", n:"" },

  // ── METAL OXIDES ──
  { cat:"metal-oxides", cl:"c-hydro",
    f:"Metal oxide + H₂O: which are soluble?", fs:"",
    b:"Na⁺ to Cs⁺ (soluble); Ba²⁺, Sr²⁺, Ca²⁺ (partially soluble)", bs:"Most others are insoluble",
    n:"Metal oxides with metal in high OS (≥5) are water soluble and form strong acids" },
  { cat:"metal-oxides", cl:"c-hydro",
    f:"CrO₃ + H₂O → ?", fs:"Cr in +6 (≥5)", b:"H₂CrO₄", bs:"Strong acid", n:"" },
  { cat:"metal-oxides", cl:"c-hydro",
    f:"MnO₃ / Mn₂O₇ + H₂O → ?", fs:"Mn in high OS", b:"H₂MnO₄ / HMnO₄", bs:"Strong acids", n:"" },
  { cat:"metal-oxides", cl:"c-hydro",
    f:"V₂O₅ + H₂O → ?", fs:"", b:"(HVO₃)ₙ — polymeric", bs:"", n:"" },
  { cat:"metal-oxides", cl:"c-hydro",
    f:"Bi₂O₅ + H₂O → ?", fs:"", b:"HBiO₃", bs:"", n:"" },
  { cat:"metal-oxides", cl:"c-hydro",
    f:"N₂O₅ + H₂O → ?", fs:"", b:"HNO₃", bs:"",
    n:"N₂O₅ + NaOH → NaNO₃. Reversible (non-metal oxides only)" },

  // ── HEATING — CARBONATES ──
  { cat:"heating-carbonates", cl:"c-heat",
    f:"M₂CO₃ on heating? (M = Na/K/Rb/Cs)", fs:"Alkali metal carbonates",
    b:"No decomposition", bs:"",
    n:"Exception: Li₂CO₃ → Li₂O + CO₂↑ (diagonal relationship with Mg²⁺)" },
  { cat:"heating-carbonates", cl:"c-heat",
    f:"MCO₃ on heating? (M = alkaline earth / Ca / Pb etc.)", fs:"",
    b:"MO + CO₂↑", bs:"eg: CaCO₃ → CaO + CO₂; PbCO₃ → PbO + CO₂", n:"" },
  { cat:"heating-carbonates", cl:"c-heat",
    f:"2MHCO₃ on heating? (M = Na/K/Rb/Cs)", fs:"Alkali metal bicarbonates",
    b:"M₂CO₃ + CO₂↑ + H₂O↑", bs:"",
    n:"If aq NaHCO₃ used instead of solid, liquid water is formed" },
  { cat:"heating-carbonates", cl:"c-heat",
    f:"Mg(HCO₃)₂ on heating → ?", fs:"",
    b:"Mg(OH)₂↓ + H₂O + CO₂", bs:"Solubility of Mg(OH)₂ < MgCO₃", n:"" },
  { cat:"heating-carbonates", cl:"c-heat",
    f:"Ag₂CO₃ on heating → ?", fs:"", b:"2Ag + CO₂↑ + O₂↑", bs:"Same with Hg", n:"" },

  // ── HEATING — NITRATES ──
  { cat:"heating-nitrates", cl:"c-heat",
    f:"MNO₃ on heating? (M = K/Rb/Cs)", fs:"", b:"MNO₂ + O₂↑", bs:"", n:"" },
  { cat:"heating-nitrates", cl:"c-heat",
    f:"LiNO₃ on heating → ?", fs:"", b:"Li₂O + NO₂↑ + O₂↑", bs:"",
    n:"Li behaves like Mg (diagonal relationship)" },
  { cat:"heating-nitrates", cl:"c-heat",
    f:"NaNO₃ on heating → ?", fs:"",
    b:"<500°C: NaNO₂ + O₂; >500°C: Na₂O + N₂↑ + O₂↑", bs:"", n:"" },
  { cat:"heating-nitrates", cl:"c-heat",
    f:"M(NO₃)₂ on heating? (M = Ca/Zn/Pb/Mg/Cu/Be/Sn/Ba)", fs:"",
    b:"MO(s) + NO₂↑ + O₂↑", bs:"", n:"" },

  // ── HEATING — SULPHATES ──
  { cat:"heating-sulphates", cl:"c-heat",
    f:"M₂SO₄ on heating? (M = Na/K/Rb/Cs)", fs:"",
    b:"No decomposition", bs:"", n:"Li₂SO₄ → Li₂O + SO₃↑" },
  { cat:"heating-sulphates", cl:"c-heat",
    f:"MSO₄ on heating? (M = Be/Mg/Ca/Sr/Cu/Zn)", fs:"",
    b:"MO + SO₃↑ → (>800°C) SO₂ + O₂", bs:"", n:"" },
  { cat:"heating-sulphates", cl:"c-heat",
    f:"Ag₂SO₄ on heating → ?", fs:"",
    b:"Ag + SO₃↑ + O₂↑", bs:"Same with HgSO₄",
    n:"Salts of Ag, Hg and their oxides decompose on heating" },
  { cat:"heating-sulphates", cl:"c-heat",
    f:"FeSO₄ on heating → ?", fs:"",
    b:"Fe₂O₃ + SO₂↑ + SO₃↑", bs:"", n:"Fe₂(SO₄)₃ → Fe₂O₃ + SO₃↑" },

  // ── HEATING — OXALATES ──
  { cat:"heating-oxalates", cl:"c-heat",
    f:"Na₂C₂O₄ on heating → ?", fs:"", b:"Na₂CO₃ + CO↑", bs:"", n:"" },
  { cat:"heating-oxalates", cl:"c-heat",
    f:"CaC₂O₄ on heating → ?", fs:"",
    b:"CaO + 2CO₂ + CO↑ (via CaCO₃ intermediate)", bs:"CaC₂O₄ → CaCO₃ → CaO + CO₂ (+ O₂)", n:"" },
  { cat:"heating-oxalates", cl:"c-heat",
    f:"Ag₂C₂O₄ on heating → ?", fs:"",
    b:"Ag(s) + 2CO₂↑", bs:"Via AgCO₃ → AgO → CO₂+O₂", n:"" },

  // ── HEATING — OXIDES ──
  { cat:"heating-oxides", cl:"c-heat",
    f:"K₂Cr₂O₇ on heating → ?", fs:"", b:"Cr₂O₃ + K₂CrO₄ + O₂↑", bs:"", n:"" },
  { cat:"heating-oxides", cl:"c-heat",
    f:"KMnO₄ on heating → ?", fs:"", b:"MnO₂ + K₂MnO₄ + O₂↑", bs:"", n:"" },
  { cat:"heating-oxides", cl:"c-heat",
    f:"PbO₂ on heating → ?", fs:"", b:"PbO + O₂↑", bs:"", n:"Pb₃O₄ → PbO + O₂↑" },
  { cat:"heating-oxides", cl:"c-heat",
    f:"MnO₂ on heating → ?", fs:"",
    b:"Mn₃O₄ + O₂↑ (Mn₂O₃ intermediate)", bs:"",
    n:"Ag₂O → Ag + O₂↑; HgO → Hg(l) + O₂↑" },
  { cat:"heating-oxides", cl:"c-heat",
    f:"Al₂O₃ / ZnO / CuO / MgO / Fe₂O₃ on heating → ?", fs:"",
    b:"No decomposition", bs:"", n:"Au₂O₃ / PtO₂ decompose at room temperature" },

  // ── HEATING — NH4 SALTS ──
  { cat:"heating-NH4", cl:"c-heat",
    f:"NH₄X on heating? (X = Cl/Br/I)", fs:"Ammonium halides", b:"NH₃↑ + HX↑", bs:"", n:"" },
  { cat:"heating-NH4", cl:"c-heat",
    f:"(NH₄)₂SO₄ on heating → ?", fs:"", b:"2NH₃ + H₂SO₄", bs:"", n:"" },
  { cat:"heating-NH4", cl:"c-heat",
    f:"NH₄HS on heating → ?", fs:"", b:"NH₃ + H₂S", bs:"", n:"" },
  { cat:"heating-NH4", cl:"c-heat",
    f:"NH₄NO₂ on heating → ?", fs:"Anion is oxidising",
    b:"N₂↑ + 2H₂O↑", bs:"OS of N: +3 and -3 → 0",
    n:"Thermal decomp — anion oxidising → N₂ or N₂O as product" },
  { cat:"heating-NH4", cl:"c-heat",
    f:"NH₄NO₃ on heating → ?", fs:"", b:"N₂O↑ + H₂O↑", bs:"N: +5 and -3 → +1", n:"" },
  { cat:"heating-NH4", cl:"c-heat",
    f:"N₂H₅NO₂ on heating → ?", fs:"Hydrazinium nitrite",
    b:"HN₃ + H₂O (hydrazoic acid — explosive!)", bs:"H−N=N=N", n:"" },
  { cat:"heating-NH4", cl:"c-heat",
    f:"NH₄ClO₄ on heating → ?", fs:"", b:"N₂↑ + Cl₂↑ + O₂↑ + H₂O↑", bs:"", n:"" },
  { cat:"heating-NH4", cl:"c-heat",
    f:"NH₄IO₃ on heating → ?", fs:"", b:"N₂↑ + H₂O↑ + I₂ + O₂", bs:"", n:"" },
  { cat:"heating-NH4", cl:"c-heat",
    f:"(NH₄)₂Cr₂O₇ on heating → ?", fs:"Orange crystals — used in crackers",
    b:"N₂↑ + H₂O↑ + Cr₂O₃ (green solid)", bs:"", n:"" },

  // ── HEATING — AZIDES ──
  { cat:"heating-azides", cl:"c-heat",
    f:"NaN₃ on heating → ?", fs:"Metal azide — airbags",
    b:"Na + N₂↑ (very pure N₂)", bs:"",
    n:"Metal azides are explosive. Ba(N₃)₂ → Ba + N₂↑" },
  { cat:"heating-azides", cl:"c-heat",
    f:"HN₃ on heating → ?", fs:"Hydrazoic acid", b:"½H₂ + N₂↑", bs:"", n:"" },

  // ── HEATING — ACIDS ──
  { cat:"heating-acids", cl:"c-heat",
    f:"H₂C₂O₄ on heating → ?", fs:"Oxalic acid", b:"H₂O↑ + CO↑ + CO₂↑", bs:"", n:"" },
  { cat:"heating-acids", cl:"c-heat",
    f:"H₃PO₂ on heating → ?", fs:"Hypophosphorous acid",
    b:"H₃PO₃ + PH₃↑ → (more heat) H₃PO₄ + PH₃↑", bs:"", n:"" },
  { cat:"heating-acids", cl:"c-heat",
    f:"HNO₂ on warming → ?", fs:"Nitrous acid (unstable)",
    b:"HNO₃ + NO↑ + H₂O", bs:"", n:"" },
  { cat:"heating-acids", cl:"c-heat",
    f:"H₂SO₃ on heating → ?", fs:"", b:"H₂O + SO₂↑", bs:"", n:"" },
  { cat:"heating-acids", cl:"c-heat",
    f:"H₃PO₄ on heating → ?", fs:"Chain of thermal dehydration",
    b:"→ H₄P₂O₇ (pyrophosphoric) → (HPO₃)ₙ (polymetaphosphoric) → P₄O₁₀", bs:"", n:"" },
  { cat:"heating-acids", cl:"c-heat",
    f:"H₂SO₄ on heating → ?", fs:"",
    b:"→ H₂S₂O₇ (pyrosulphuric) → SO₃ → (>800°C) SO₂ + O₂↑", bs:"", n:"" },
  { cat:"heating-acids", cl:"c-heat",
    f:"H₃BO₃ on heating → ?", fs:"", b:"B₂O₃ + H₂O↑", bs:"",
    n:"H₄SiO₃ → SiO₂ + H₂O↑" },

  // ── HEATING — SALTS ──
  { cat:"heating-salts", cl:"c-heat",
    f:"NaH₂PO₄ on heating → ?", fs:"Sodium dihydrogen phosphate",
    b:"H₂O + NaPO₃ (sodium metaphosphate — polymeric (NaPO₃)ₙ)", bs:"",
    n:"Calgon: (NaPO₃)ₙ removes permanent hardness by forming soluble complex with Ca²⁺/Mg²⁺" },
  { cat:"heating-salts", cl:"c-heat",
    f:"2Na₂HPO₄ on heating → ?", fs:"",
    b:"Na₄P₂O₇ + H₂O↑ (sodium pyrophosphate)", bs:"", n:"" },
  { cat:"heating-salts", cl:"c-heat",
    f:"Na(NH₄)HPO₄·4H₂O on heating → ?", fs:"Microcosmic salt",
    b:"NaPO₃ + H₂O↑ + NH₃↑", bs:"", n:"" },
  { cat:"heating-salts", cl:"c-heat",
    f:"2Mg(NH₄)PO₄ on heating → ?", fs:"", b:"2NH₃↑ + H₂O↑ + Mg₂P₂O₇", bs:"", n:"" },

  // ── INTERNAL HYDROLYSIS ──
  { cat:"internal-hydrolysis", cl:"c-hydro",
    f:"MCl₂·6H₂O on heating? (M = Ba/Sr/Ca)", fs:"Hydrated ionic chlorides",
    b:"MCl₂ + 6H₂O↑ (no hydrolysis)", bs:"Dominant ionic character prevents hydrolysis", n:"" },
  { cat:"internal-hydrolysis", cl:"c-hydro",
    f:"FeCl₃ on heating → ?", fs:"Hydrated salt — internal hydrolysis",
    b:"FeCl₂ + Cl₂↑", bs:"", n:"HgCl₂ → HgCl + Hg(l); PbCl₄ → PbCl₂ + Cl₂" },
  { cat:"internal-hydrolysis", cl:"c-hydro",
    f:"MgCl₂·6H₂O on heating → ?", fs:"Hydrated Mg chloride",
    b:"MgO + HCl↑ + H₂O↑ (internal hydrolysis)", bs:"",
    n:"To prevent: heat in dry HCl atmosphere → MgCl₂ + H₂O↑" },
  { cat:"internal-hydrolysis", cl:"c-hydro",
    f:"FeCl₃·6H₂O on heating → ?", fs:"",
    b:"Fe₂O₃ + 7HCl↑ + H₂O↑", bs:"", n:"AlCl₃·6H₂O → Al₂O₃ + 6HCl + H₂O" },

  // ── REDOX ──
  { cat:"redox", cl:"c-redox",
    f:"Common oxidising agents — list the key ones", fs:"",
    b:"KMnO₄, K₂Cr₂O₇, conc HNO₃, conc H₂SO₄, F₂, Cl₂, Br₂, I₂, MnO₂, O₃, O₂, H₂O₂, PbO₂, BiO₃⁻, Ca²⁺/Au³⁺/Ag⁺, KO₂/KO₃, NaOCl, XClO₃, XIO₃, XeF₂, XeF₄",
    bs:"XeF₂/XeF₄ remove O₂ from H₂O",
    n:"F₂, Cl₂, Br₂ are strong OA. I₂ is weak. H₂O₂ is powerful OA in acidic medium" },
  { cat:"redox", cl:"c-redox",
    f:"S₂O₃²⁻ with strong OA → ? with weak OA (I₂) → ?", fs:"Thiosulphate",
    b:"Strong OA: SO₄²⁻; Weak OA (I₂): S₄O₆²⁻ (tetrathionate)", bs:"",
    n:"Principle action = reducing. Called reducing bleach. H₂O₂ principle action = oxidation → oxidising bleach" },
  { cat:"redox", cl:"c-redox",
    f:"Common reducing agents — key list", fs:"",
    b:"Metals, NaH/LiAlH₄, HI, PH₃, H₂S, AsH₃, H₂, C, CO, N₂H₄, NH₂OH, H₂C₂O₄, SnCl₂, SO₂, H₂O₂, Na₂S₂O₃, S₃PO₂, S₅PO₃, B₂H₆, NaBH₄",
    bs:"H₂C₂O₄ and SO₂ are primarily OA sometimes", n:"N₂H₄ is rocket fuel" },

  // ── AMPHOTERIC METALS ──
  { cat:"misc", cl:"c-misc",
    f:"Al / Zn + HCl → ?", fs:"Amphoteric metals — react with both acid and base",
    b:"AlCl₃ / ZnCl₂ + H₂↑", bs:"", n:"Al/Zn + NaOH → NaAlO₂/Na₂ZnO₂ + H₂↑" },
  { cat:"misc", cl:"c-misc",
    f:"NO₃⁻/NO₂⁻/SCN⁻/[Fe(CN)₆]³⁻ + Zn/Al + OH⁻ → ?", fs:"",
    b:"NH₃↑", bs:"", n:"SO₃²⁻ + Zn/Al + HCl → H₂S↑ + Zn²⁺/Al³⁺" },

  // ── DEHYDRATION ──
  { cat:"dehydration", cl:"c-dehy",
    f:"H₂C₂O₄ + conc H₂SO₄ → ?", fs:"Oxalic acid + conc H₂SO₄",
    b:"CO↑ + CO₂↑ (water released but instantly dehydrated)", bs:"",
    n:"HCOOH + conc H₂SO₄ → CO↑" },
  { cat:"dehydration", cl:"c-dehy",
    f:"COOH−CH₂−COOH + conc H₂SO₄ → ?", fs:"Malonic acid",
    b:"C₃O₂ (carbon suboxide) — sp hybridised O=C=C=C=O", bs:"", n:"" },
  { cat:"dehydration", cl:"c-dehy",
    f:"C₆H₁₂O₆ + conc H₂SO₄ → ?", fs:"Glucose",
    b:"6C(s) — black ppt (charring action)", bs:"", n:"" },
  { cat:"dehydration", cl:"c-dehy",
    f:"KCN / K₄[Fe(CN)₄] + dil H₂SO₄ → ?", fs:"Cyanide salts",
    b:"HCN↑ (toxic vapours)", bs:"", n:"With conc H₂SO₄ → CO↑" },

  // ── ACID STRENGTH ──
  { cat:"acid-strength", cl:"c-acid",
    f:"Oxyacid strength rule: O=ₙX(OH)ₘ — when is it strong?", fs:"",
    b:"n − m ≥ 2 → strong acid; n − m < 2 → weak acid", bs:"",
    n:"H₂SO₄: (OH)₂SO₂, n−m=2 → strong. H₂SO₃: (OH)₂SO, n−m=0 → weak. HNO₃: (OH)NO₂, n−m=1 → strong." },
  { cat:"acid-strength", cl:"c-acid",
    f:"H₃PO₄ / H₃PO₃ / H₃PO₂ — strong or weak?", fs:"",
    b:"All weak acids", bs:"(OH)₃PO / (OH)₂HPO / (OH)H₂PO — n−m < 2 in all",
    n:"HClO₄ and HClO₃ → (OH)ClO₃/(OH)ClO₂ → both strong. HClO₂ and HClO → weak" },
  { cat:"acid-strength", cl:"c-acid",
    f:"H₄P₂O₇ (pyrophosphoric) — strong or weak?", fs:"",
    b:"Weak — average 'p' = 3/2 = 1.5, n−m <2", bs:"",
    n:"All hydroacids are weak except HCl, HBr, HI. All carboxylic acids are weak." },
];
