window.LABELS = {
  'alkane-prep':    'Alkane Prep',
  'alkane-rxn':     'Alkane Rxns',
  'alkene-prep':    'Alkene Prep',
  'alkene-rxn':     'Alkene Rxns',
  'alkyne-prep':    'Alkyne Prep',
  'alkyne-rxn':     'Alkyne Rxns',
  'stereochem':     'Stereo/Selectivity',
};

window.FILTER_GROUPS = [
  { label: 'Alkanes',  cats: ['alkane-prep', 'alkane-rxn'] },
  { label: 'Alkenes',  cats: ['alkene-prep', 'alkene-rxn'] },
  { label: 'Alkynes',  cats: ['alkyne-prep', 'alkyne-rxn'] },
  { label: 'Stereo',   cats: ['stereochem'] },
];

window.CARDS = [

  // ══ ALKANE PREPARATION ══

  { cat:'alkane-prep', cl:'c-org-a',
    f:'Alkene / Alkyne + H₂ → Alkane\nConditions?',
    fs:'Catalytic hydrogenation',
    b:'H₂, 25°C, Ni/Pd/Pt/Rh catalyst\n(syn addition)',
    bs:'Sabatier–Senderens rxn when Raney Ni used at high temp',
    n:'Both alkenes AND alkynes → alkane (excess H₂). Raney Ni = specially activated Ni.' },

  { cat:'alkane-prep', cl:'c-org-a',
    f:'Wurtz reaction: 2R-X + 2Na → ?',
    fs:'From alkyl halides, dry ether',
    b:'R-R + 2NaX',
    bs:'Mixed Wurtz: R-X + R′-X + 2Na → R-R, R-R′, R′-R′ (mixture)',
    n:'Only useful for symmetric alkanes (same R). Mixed gives uncontrolled mixture. Solvent = dry ether.' },

  { cat:'alkane-prep', cl:'c-org-a',
    f:'Corey–House synthesis:\nR-X + 2Li → ? then + CuX → ? then + R′-X → ?',
    fs:'Best way to make unsymmetric alkanes',
    b:'R-X + 2Li → RLi + LiX\n2RLi + CuX → R₂CuLi (lithium dialkylcuprate)\nR₂CuLi + R′-X → R-R′ + RCu + LiX',
    bs:'R₂CuLi does NOT react with -NO₂, -CN, C=O, ester groups',
    n:'Advantage over Wurtz: can make mixed alkane cleanly. Cuprate is selective.' },

  { cat:'alkane-prep', cl:'c-org-a',
    f:'Frankland reagent: R-X + Zn + R-X → ?',
    fs:'Dry ether',
    b:'R-R + ZnX₂',
    bs:'Same R on both sides only',
    n:'Less used — Wurtz/Corey-House preferred.' },

  { cat:'alkane-prep', cl:'c-org-a',
    f:'Grignard route to alkane:\nRMgX + R′-X → ?',
    fs:'',
    b:'R-R′ + MgX₂',
    bs:'Also: RMgX + H₂O/R′OH → R-H (protodemetalation)',
    n:'RMgX + active H (H₂O, alcohol, NH₃, terminal alkyne) → R-H.' },

  { cat:'alkane-prep', cl:'c-org-a',
    f:'Reduction of alkyl halide with metal-acid:\nR-X → R-H. Reagents?',
    fs:'',
    b:'Zn/acid, Zn-Cu/H₂O, Na-Hg/acid, Al-Hg/H₂O',
    bs:'',
    n:'' },

  { cat:'alkane-prep', cl:'c-org-a',
    f:'Reduction of R-X with metal hydride:\nR-X → R-H. Which hydrides for 1°/2°/3°?',
    fs:'',
    b:'TBH (Ph₃SnH) → 1°, 2°, 3°\nNaBH₄ → 2°, 3°\nLiAlH₄ (LiAeH₄) → 1°, 2°\n3° R-X + LiAlH₄ → ALKENE (elimination!)',
    bs:'',
    n:'3° with LiAlH₄ gives elimination, not reduction.' },

  { cat:'alkane-prep', cl:'c-org-a',
    f:'Decarboxylation by soda-lime:\nR-COOH → ?',
    fs:'',
    b:'R-COOH + NaOH → R-COONa + CaO/Δ → R-H + Na₂CO₃',
    bs:'Product has one fewer carbon than acid',
    n:'Soda-lime = NaOH + CaO. CaO acts as dehydrating agent.' },

  { cat:'alkane-prep', cl:'c-org-a',
    f:'Kolbe\'s electrolysis:\n2R-COOK + 2HOH → ?',
    fs:'Electrolysis',
    b:'R-R + H₂ + 2CO₂ + 2KOH',
    bs:'Anode: RCOO⁻ → R• → R-R; Cathode: H⁺ → H₂',
    n:'Gives symmetric alkane. Lose COOH group, gain C-C bond.' },

  { cat:'alkane-prep', cl:'c-org-a',
    f:'Decarboxylation of β-keto acid on heating → ?',
    fs:'',
    b:'CH₃-CO-CH₂-COOH + Δ → CH₃-CO-CH₃ (acetone) + CO₂',
    bs:'β-keto acids decarboxylate easily',
    n:'The β-keto group stabilises the transition state.' },

  { cat:'alkane-prep', cl:'c-org-a',
    f:'Clemmensen\'s reduction:\nR-CO-R′ → ?\nReagents?',
    fs:'Reduces C=O to CH₂',
    b:'R-CH₂-R′ + H₂O\nR-CHO → R-CH₃',
    bs:'Reagent: Zn-Hg / conc. HCl',
    n:'NOT used with acid-sensitive groups. Acidic conditions.' },

  { cat:'alkane-prep', cl:'c-org-a',
    f:'Wolff–Kishner reduction:\nR-CO-R′ → ?\nReagents?',
    fs:'Reduces C=O to CH₂',
    b:'R-CH₂-R′ + H₂O\nReagent: NH₂-NH₂ / KOH, high boiling solvent (ethylene glycol)',
    bs:'NOT used with base-sensitive groups',
    n:'Basic conditions — complement to Clemmensen (acidic). sp² → sp³.' },

  // ══ ALKANE REACTIONS ══

  { cat:'alkane-rxn', cl:'c-org-a',
    f:'Alkane combustion formula:\nCₙH₂ₙ₊₂ + O₂ → ?',
    fs:'',
    b:'CₙH₂ₙ₊₂ + (3n+1)/2 O₂ → nCO₂ + (n+1)H₂O',
    bs:'',
    n:'Heat of combustion ∝ 1/stability of alkane. Also: heat of combustion ∝ 1/heat of hydrogenation.' },

  { cat:'alkane-rxn', cl:'c-org-a',
    f:'Halogenation of alkane:\nR-H + X₂ → ? Conditions?',
    fs:'Free radical substitution',
    b:'R-X + HX\nReagent: UV (hν) or 250–400°C',
    bs:'Reactivity of X₂: F₂ > Cl₂ > Br₂ (I₂ too slow — reversible)',
    n:'Selectivity: Br₂ > Cl₂ (Br more selective). % Yield = Relative Yield × 100 / Total Yield.' },

  { cat:'alkane-rxn', cl:'c-org-a',
    f:'Chlorination reagents for alkanes (4 options)?',
    fs:'',
    b:'1) Cl₂/hν\n2) SO₂Cl₂/R₂O₂\n3) t-BuO-Cl\n4) Cl₂/R₂O₂',
    bs:'',
    n:'' },

  { cat:'alkane-rxn', cl:'c-org-a',
    f:'Bromination reagents for alkanes (4 options)?',
    fs:'',
    b:'1) Br₂/hν\n2) SO₂Br₂/R₂O₂\n3) t-BuO-Br\n4) Br₂/R₂O₂',
    bs:'',
    n:'NBS (N-bromosuccinimide) = allylic/benzylic bromination.' },

  { cat:'alkane-rxn', cl:'c-org-a',
    f:'Iodination of alkane: R-H + I₂ → ?\nHow to drive it forward?',
    fs:'',
    b:'R-I + HI (equilibrium, reversible)\nAdd HNO₃ or HIO₃ to oxidise HI and drive forward',
    bs:'I₂ + HNO₃ or I₂ + HIO₃ as reagent',
    n:'' },

  { cat:'alkane-rxn', cl:'c-org-a',
    f:'Fluorination of alkane: R-H + F₂ → ?\nHow to control?',
    fs:'',
    b:'R-F + HF (violent — needs control)\nDiluted with N₂ in dark environment',
    bs:'',
    n:'F₂ too reactive — explosive without dilution/dark conditions.' },

  // ══ ALKENE PREPARATION ══

  { cat:'alkene-prep', cl:'c-org-b',
    f:'Partial reduction of alkyne → cis-alkene:\nReagents?',
    fs:'Syn addition — Lindlar\'s or P-2 catalyst',
    b:'Lindlar\'s catalyst: Pd deposited on CaCO₃ + lead acetate/quinoline\nP-2 catalyst: Ni₂B (nickel boride)',
    bs:'Gives cis (Z) alkene',
    n:'Both poisoned catalysts slow down H₂ so stops at alkene. Lindlar\'s = most important.' },

  { cat:'alkene-prep', cl:'c-org-b',
    f:'Birch reduction of alkyne → trans-alkene:\nReagents?',
    fs:'Anti addition',
    b:'Na/Li in liquid NH₃ (Na/NH₃)\nGives trans (E) alkene',
    bs:'Does NOT work with terminal alkynes',
    n:'Anti addition → trans product. Works only on internal alkynes.' },

  { cat:'alkene-prep', cl:'c-org-b',
    f:'Dehydration of alcohol → alkene:\nReagents?',
    fs:'β-elimination (E1)',
    b:'1) H₂SO₄/160°C\n2) H₃PO₄/Δ\n3) P₂O₅/Δ\n4) Al₂O₃/350°C',
    bs:'β-carbon loses H, α-carbon loses OH',
    n:'Saytzeff product (more substituted alkene) is major product.' },

  { cat:'alkene-prep', cl:'c-org-b',
    f:'Dehydrohalogenation of alkyl halide → alkene:\nReagents?',
    fs:'E2 mechanism, anti elimination',
    b:'1) Hot alc. KOH or NaOH\n2) NaNH₂\n3) t-BuOK in t-BuOH\n4) EtO⁻/EtOH',
    bs:'Saytzeff product is major (unless bulky base → Hofmann)',
    n:'Hot alcoholic KOH = classic E2. Bulky base (t-BuOK) → less substituted (Hofmann) product.' },

  { cat:'alkene-prep', cl:'c-org-b',
    f:'Dehalogenation of vicinal dihalide → alkene:\nReagents?',
    fs:'Anti elimination (E2)',
    b:'vic-dihalide + NaI in acetone\nOR Zn dust in acetic acid / ethanol',
    bs:'X\n|\n-C-C- + Zn → -C=C- + ZnX₂\n|\nX',
    n:'' },

  // ══ ALKENE REACTIONS ══

  { cat:'alkene-rxn', cl:'c-org-b',
    f:'Alkene + H₂ → ? Mechanism type?',
    fs:'',
    b:'Alkane (syn addition)\nCatalyst: Ni/Pd/Pt, 25°C',
    bs:'',
    n:'Same reagents as alkyne → alkane but stops at alkane (excess H₂).' },

  { cat:'alkene-rxn', cl:'c-org-b',
    f:'Markovnikov\'s rule — state it',
    fs:'For HX addition to alkene',
    b:'H adds to C with more H already (less substituted C)\nX adds to more substituted C (more stable carbocation)',
    bs:'Anti-Markovnikov: use radical conditions (ROOR/hν with HBr only)',
    n:'Anti-Markovnikov only with HBr + peroxide. HCl/HI don\'t give anti-Markov even with peroxide.' },

  { cat:'alkene-rxn', cl:'c-org-b',
    f:'Alkene + H₂O (hydration) → alcohol. Reagents?',
    fs:'',
    b:'Acid-catalysed: H₂SO₄/H₃PO₄ + H₂O → Markovnikov alcohol\nHydroboration-oxidation (BH₃/THF then H₂O₂/NaOH) → anti-Markovnikov, syn addition',
    bs:'',
    n:'Oxymercuration-demercuration also gives Markovnikov without rearrangement.' },

  { cat:'alkene-rxn', cl:'c-org-b',
    f:'Alkene + X₂ (Cl₂/Br₂) → ? Type of addition?',
    fs:'Halogen addition',
    b:'Vicinal dihalide (-CHX-CHX-)\nAnti addition (trans product)',
    bs:'Reagent: Br₂ in CCl₄ (decolorisation = test for alkene)\nCl₂ in CCl₄',
    n:'Electrophilic addition via halonium ion intermediate → anti product.' },

  { cat:'alkene-rxn', cl:'c-org-b',
    f:'Alkene + Br₂/H₂O → ? (halohydrin)',
    fs:'',
    b:'Bromohydrin: -CH(OH)-CH(Br)- (anti addition)\nMarkovnikov: OH on more substituted C',
    bs:'',
    n:'Water acts as nucleophile — OH goes to more substituted carbon.' },

  { cat:'alkene-rxn', cl:'c-org-b',
    f:'Ozonolysis of alkene:\nR-CH=CH-R′ + O₃ → ? (reductive vs oxidative workup)',
    fs:'',
    b:'Reductive (Zn/H₂O or DMS): aldehydes/ketones\nOxidative (H₂O₂): carboxylic acids (RCHO → RCOOH)\nR₂C= always gives ketone in both',
    bs:'',
    n:'Use to determine structure. R-CH= → RCHO (reductive) or RCOOH (oxidative).' },

  { cat:'alkene-rxn', cl:'c-org-b',
    f:'Alkene + KMnO₄ → ? (cold dilute vs hot conc.)',
    fs:'',
    b:'Cold dil. KMnO₄ (Baeyer\'s test): syn dihydroxylation → vicinal diol (brown ppt turns colourless)\nHot conc. KMnO₄: oxidative cleavage → RCOOH / ketone / CO₂',
    bs:'',
    n:'Baeyer\'s test: KMnO₄ decolorises = unsaturation present. Brown MnO₂ precipitates.' },

  { cat:'alkene-rxn', cl:'c-org-b',
    f:'Alkene + OsO₄ → ? Type of addition?',
    fs:'',
    b:'Syn dihydroxylation → vicinal diol (cis-diol)\nSame as cold KMnO₄ but more reliable',
    bs:'',
    n:'NMO (N-methylmorpholine N-oxide) used catalytically with OsO₄.' },

  { cat:'alkene-rxn', cl:'c-org-b',
    f:'Alkene + mCPBA (peracid) → ?\nThen + H₃O⁺ → ?',
    fs:'Epoxidation',
    b:'mCPBA → epoxide (syn, retention)\n+ H₃O⁺ → trans diol (anti addition overall)',
    bs:'',
    n:'Epoxide ring opening by H₃O⁺ is anti → trans-diol. Compare with OsO₄/KMnO₄ = cis-diol.' },

  // ══ ALKYNE PREPARATION ══

  { cat:'alkyne-prep', cl:'c-org-c',
    f:'Dehalogenation of tetrahalide → alkyne:\nReagents?',
    fs:'',
    b:'R-CX₂-CX₂-R′ + 2Zn dust/alcohol/Δ → R-C≡C-R′ + 2ZnX₂\nCHCl₃ + 6Ag + C₂H₅OH → CH≡CH + 6AgCl',
    bs:'',
    n:'' },

  { cat:'alkyne-prep', cl:'c-org-c',
    f:'Dehydrohalogenation of vic/gem-dihalide → alkyne:\nReagents?',
    fs:'',
    b:'vic-dihalide + 2NaNH₂ → alkyne\nalc. KOH gives vinyl halide (intermediate) → alkyne with stronger base',
    bs:'NaNH₂, LiNH₂, KNH₂ or alc. KOH',
    n:'Two steps of elimination. vic-dihalide → vinyl halide → alkyne.' },

  { cat:'alkyne-prep', cl:'c-org-c',
    f:'Terminal alkyne → higher internal alkyne.\nReagents?',
    fs:'Replacement of acetylenic H',
    b:'R-C≡C-H + NaNH₂ → R-C≡C⁻Na⁺ + R′-X → R-C≡C-R′',
    bs:'Na amide deprotonates terminal alkyne (pKa ≈ 25)',
    n:'Only terminal alkynes have acidic H (pKa ~25). Internal alkynes cannot do this.' },

  // ══ ALKYNE REACTIONS ══

  { cat:'alkyne-rxn', cl:'c-org-c',
    f:'Alkyne + H₂ (1 equiv) → ? (syn vs anti)',
    fs:'Two possible routes',
    b:'Lindlar\'s/P-2 → cis-alkene (syn addition)\nNa/NH₃ (Birch) → trans-alkene (anti addition)',
    bs:'+ excess H₂ → alkane',
    n:'Critical distinction: Lindlar = syn/cis; Na/NH₃ = anti/trans. Birch doesn\'t work on terminal alkynes.' },

  { cat:'alkyne-rxn', cl:'c-org-c',
    f:'Alkyne + HX (1 equiv) → ? (2 equiv) → ?',
    fs:'Markovnikov addition',
    b:'1 equiv HX → vinyl halide (Markovnikov)\n2 equiv HX → gem-dihalide (both X on same C)',
    bs:'',
    n:'Terminal alkyne: H adds to terminal C, X to internal C (Markovnikov).' },

  { cat:'alkyne-rxn', cl:'c-org-c',
    f:'Hydration of alkyne (Markovnikov):\nR-C≡CH + H₂O → ?',
    fs:'Keto-enol tautomerism',
    b:'H₂SO₄/HgSO₄ catalyst → enol → ketone (Markovnikov)\nTerminal alkyne → methyl ketone (R-CO-CH₃)\nAcetylene → acetaldehyde (CH₃CHO)',
    bs:'',
    n:'Enol immediately tautomerises to more stable keto form.' },

  { cat:'alkyne-rxn', cl:'c-org-c',
    f:'Hydration of alkyne (anti-Markovnikov):\nHydroboration-oxidation → ?',
    fs:'',
    b:'BH₃/THF (syn) → vinyl borane → H₂O₂/NaOH → aldehyde\nTerminal alkyne → aldehyde (anti-Markovnikov)',
    bs:'',
    n:'Compare: acid/HgSO₄ = Markovnikov = ketone; Hydroboration = anti-Markovnikov = aldehyde.' },

  { cat:'alkyne-rxn', cl:'c-org-c',
    f:'Acidic nature of terminal alkyne:\nR-C≡C-H + NaNH₂ → ?\nR-C≡C-H + AgNO₃/NH₃ → ?\nR-C≡C-H + Cu₂Cl₂/NH₄OH → ?',
    fs:'pKa of terminal alkyne ≈ 25',
    b:'+ NaNH₂ → R-C≡C-Na (sodium acetylide)\n+ AgNO₃/NH₃ → R-C≡C-Ag↓ (white ppt)\n+ Cu₂Cl₂/NH₄OH → R-C≡C-Cu↓ (red/brown ppt)',
    bs:'',
    n:'Acidity: RC≡CH > H₂O > ROH > NH₃ > RH. Silver/copper acetylides explosive when dry!' },

  { cat:'alkyne-rxn', cl:'c-org-c',
    f:'Ozonolysis of alkyne:\nR-C≡C-R′ + O₃ → then H₂O → ?',
    fs:'',
    b:'Carboxylic acids: RCOOH + R′COOH\nTerminal alkyne: RCOOH + CO₂ + H₂O',
    bs:'',
    n:'Alkynes give acids directly (not aldehydes) unlike alkenes.' },

  // ══ STEREOCHEMISTRY / SELECTIVITY ══

  { cat:'stereochem', cl:'c-org-d',
    f:'Syn vs Anti addition — what gives each?',
    fs:'',
    b:'SYN (same face):\n• H₂/Lindlar\'s → cis-alkene\n• BH₃ (hydroboration)\n• OsO₄/KMnO₄ cold → cis-diol\n• mCPBA → epoxide\nANTI (opposite face):\n• X₂ (via halonium)\n• Birch reduction → trans-alkene\n• Epoxide opening with H₃O⁺',
    bs:'',
    n:'' },

  { cat:'stereochem', cl:'c-org-d',
    f:'Saytzeff\'s rule vs Hofmann\'s rule',
    fs:'Which alkene product is major?',
    b:'Saytzeff: more substituted alkene is major product (normal E2 with small base)\nHofmann: less substituted alkene is major product (bulky base like t-BuOK)',
    bs:'',
    n:'Bulky base cannot access internal H → attacks least hindered H → less substituted product.' },

  { cat:'stereochem', cl:'c-org-d',
    f:'Relative reactivity of H for free-radical halogenation:\nwhich C-H is most reactive?',
    fs:'',
    b:'3° > 2° > 1° > CH₄ (for both Cl₂ and Br₂)\nBr₂ more selective: ratio 3°:2°:1° ≈ 1600:82:1\nCl₂ less selective: ratio 3°:2°:1° ≈ 5:3.8:1',
    bs:'',
    n:'Selectivity ∝ 1/reactivity. Br more selective because Br• is less reactive → more choosy.' },

  { cat:'stereochem', cl:'c-org-d',
    f:'Stability order of alkenes?',
    fs:'',
    b:'More substituted = more stable\nR₂C=CR₂ > R₂C=CHR > R₂C=CH₂ > RCH=CHR (trans > cis) > RCH=CH₂ > CH₂=CH₂',
    bs:'trans > cis for disubstituted',
    n:'Heat of hydrogenation: more stable alkene has lower ΔH (releases less heat on hydrogenation).' },

];
