window.LABELS = {
  'group-overview':'Group Overview', 'nh4-tests':'NH₄⁺ Tests',
  'pb-rxns':'Pb²⁺', 'ag-rxns':'Ag⁺', 'hg2-rxns':'Hg₂²⁺',
  'hg-rxns':'Hg²⁺', 'bi-rxns':'Bi³⁺', 'cu-rxns':'Cu²⁺', 'cd-rxns':'Cd²⁺',
  'as-rxns':'As³⁺',
  'al-rxns':'Al³⁺', 'cr-rxns':'Cr³⁺', 'fe-rxns':'Fe²⁺/Fe³⁺',
  'co-rxns':'Co²⁺', 'ni-rxns':'Ni²⁺', 'mn-rxns':'Mn²⁺', 'zn-rxns':'Zn²⁺',
  'ba-rxns':'Ba²⁺', 'sr-rxns':'Sr²⁺', 'ca-rxns':'Ca²⁺',
  'mg-rxns':'Mg²⁺',
};

window.FILTER_GROUPS = [
  { label:'Overview & NH₄⁺', cats:['group-overview','nh4-tests'] },
  { label:'Group 1',  cats:['pb-rxns','ag-rxns','hg2-rxns'] },
  { label:'Group 2A', cats:['hg-rxns','bi-rxns','cu-rxns','cd-rxns'] },
  { label:'Group 2B', cats:['as-rxns'] },
  { label:'Group 3',  cats:['al-rxns','cr-rxns','fe-rxns'] },
  { label:'Group 4',  cats:['co-rxns','ni-rxns','mn-rxns','zn-rxns'] },
  { label:'Group 5',  cats:['ba-rxns','sr-rxns','ca-rxns'] },
  { label:'Group 6',  cats:['mg-rxns'] },
];

window.CARDS = [
  // ── GROUP OVERVIEW ──
  { cat:'group-overview', cl:'c-qa-grp1',
    f:'Group 1 cations + Group reagent → ?', fs:'Ag⁺, Pb²⁺, Hg₂²⁺',
    b:'Ag⁺ + dil HCl → AgCl↓ (white)\nPb²⁺ + dil HCl → PbCl₂↓ (white)\nHg₂²⁺ + dil HCl → Hg₂Cl₂↓ (white)', bs:'All white ppts', n:'' },
  { cat:'group-overview', cl:'c-qa-grp2a',
    f:'Group 2A cations + Group reagent → ?', fs:'Pb²⁺, Cu²⁺, Bi³⁺, Hg²⁺, Cd²⁺',
    b:'H₂S(g) + dil HCl:\nPbS↓, CuS↓, Bi₂S₃↓, HgS↓ (Black)\nCdS↓ (Yellow)',
    bs:'2A insoluble in YAS', n:'' },
  { cat:'group-overview', cl:'c-qa-grp2b',
    f:'Group 2B cations + Group reagent → ?', fs:'As³⁺, Sn²⁺, Sn⁴⁺, Sb³⁺',
    b:'H₂S + dil HCl:\nAs₂S₃↓, SnS₂↓ (Yellow); SnS↓ (Brown); Sb₂S₃↓ (Orange)',
    bs:'2B soluble in YAS = (NH₄)₂Sₓ (x=2,3,5)', n:'' },
  { cat:'group-overview', cl:'c-qa-grp3',
    f:'Group 3 cations + Group reagent → ?', fs:'Al³⁺, Cr³⁺, Fe³⁺',
    b:'NH₄OH + NH₄Cl:\nAl(OH)₃↓ (gelatinous white)\nCr(OH)₃↓ (dirty green)\nFe(OH)₃↓ (reddish brown)', bs:'', n:'' },
  { cat:'group-overview', cl:'c-qa-grp4',
    f:'Group 4 cations + Group reagent → ?', fs:'Zn²⁺, Ni²⁺, Co²⁺, Mn²⁺',
    b:'H₂S + NH₄OH + NH₄Cl:\nZnS↓ (dirty white); NiS↓, CoS↓ (Black); MnS↓ (light pink)', bs:'', n:'' },
  { cat:'group-overview', cl:'c-qa-grp5',
    f:'Group 5 cations + Group reagent → ?', fs:'Ba²⁺, Sr²⁺, Ca²⁺',
    b:'(NH₄)₂CO₃ + NH₄OH:\nBaCO₃↓, SrCO₃↓, CaCO₃↓ (all White)', bs:'', n:'' },
  { cat:'group-overview', cl:'c-qa-grp6',
    f:'Group 6 cation + Group reagent → ?', fs:'Mg²⁺',
    b:'Mg²⁺ + Na₂HPO₄ + NH₄OH → Mg(NH₄)PO₄↓ (White)', bs:'', n:'' },
  { cat:'group-overview', cl:'c-qa-grp7',
    f:'Group 7 cation + Group reagent → ?', fs:'NH₄⁺',
    b:'NH₄⁺ + aq. NaOH/Ca(OH)₂ → NH₃↑', bs:'', n:'' },

  // ── NH₄⁺ TESTS ──
  { cat:'nh4-tests', cl:'c-qa-nh4',
    f:'NH₄⁺ + aq NaOH → ? Detection tests?', fs:'Ammonium salt in base',
    b:'NH₄⁺ + NaOH → NH₃↑ + NaCl + H₂O\nNH₃ turns red litmus blue\nGlass rod in HCl → white fumes: NH₃ + HCl → NH₄Cl', bs:'', n:'' },
  { cat:'nh4-tests', cl:'c-qa-nh4',
    f:'Mn²⁺ + H₂O₂ + NH₃(aq) → ? (NH₃ test ii)', fs:'',
    b:'Mn²⁺ + H₂O₂ + NH₃(aq) → MnO₂·H₂O↓ + NH₄⁺\nBrown-black ppt (Hydrated MnO₂)', bs:'', n:'' },
  { cat:'nh4-tests', cl:'c-qa-nh4',
    f:'CuSO₄ + 4NH₃ → ? (deep blue test)', fs:'',
    b:'CuSO₄ + 4NH₃ → [Cu(NH₃)₄]SO₄\nDeep blue; dsp², paramagnetic, square planar', bs:'', n:'' },
  { cat:'nh4-tests', cl:'c-qa-nh4',
    f:"Nessler's Reagent (KOH + K₂HgI₄) + NH₄⁺ → ?", fs:'',
    b:"NH₄⁺ + KOH + K₂HgI₄ → HgO·Hg(NH₂)I↓ + KI + H₂O\nIodide of Millon's base — Brown ppt", bs:'', n:'' },
  { cat:'nh4-tests', cl:'c-qa-nh4',
    f:'3NH₄⁺ + Na₃[Co(NO₂)₆] → ?', fs:'',
    b:'3NH₄⁺ + Na₃[Co(NO₂)₆] → (NH₄)₃[Co(NO₂)₆]↓ + 3Na⁺\nYellow ppt', bs:'', n:'' },
  { cat:'nh4-tests', cl:'c-qa-nh4',
    f:'3NH₄⁺ + H₂PtCl₆ → ?', fs:'Hexachloroplatinic acid',
    b:'3NH₄⁺ + H₂PtCl₆ → (NH₄)₂[PtCl₆]↓ + H⁺\nYellow ppt', bs:'', n:'' },
  { cat:'nh4-tests', cl:'c-qa-nh4',
    f:'p-Nitrobenzene diazonium chloride + NH₄⁺ + OH⁻ → ?', fs:'Diazonium coupling test',
    b:'O₂N-C₆H₄-N≡NCl + NH₄⁺ + OH⁻ → O₂N-C₆H₄-N=N-NH₂ + Cl⁻ + H₂O\nRed solution', bs:'', n:'' },

  // ── GROUP 1 — Pb²⁺ ──
  { cat:'pb-rxns', cl:'c-qa-pb',
    f:'Pb²⁺ + HCl → ? conc HCl/KCl → ?', fs:'',
    b:'Pb²⁺ + 2HCl → PbCl₂↓ (white; insol cold, sol hot)\nPbCl₂ + 2HCl(conc) → [PbCl₄]²⁻(aq)', bs:'', n:'' },
  { cat:'pb-rxns', cl:'c-qa-pb',
    f:'Pb²⁺ + H₂S → ? conc HNO₃ → ? boil → ?', fs:'',
    b:'Pb²⁺ + H₂S → PbS↓ (black)\nPbS + conc HNO₃ → Pb²⁺ + S↓ + NO↑\nPb²⁺ + conc HNO₃ + boil → PbSO₄↓', bs:'', n:'' },
  { cat:'pb-rxns', cl:'c-qa-pb',
    f:'Pb²⁺ + aq NH₃ → ? excess → ?', fs:'',
    b:'Pb²⁺ + 2NH₃ + 2H₂O → Pb(OH)₂↓ (white) + 2NH₄⁺\nExcess NH₃: No dissolution', bs:'', n:'' },
  { cat:'pb-rxns', cl:'c-qa-pb',
    f:'Pb²⁺ + aq NaOH → ? excess → ? H₂O₂/Δ → ?', fs:'',
    b:'Pb²⁺ + 2NaOH → Pb(OH)₂↓\nExcess NaOH → Na₂[Pb(OH)₄]\nH₂O₂/Δ or S₂O₈²⁻ → PbO₂ (black)', bs:'', n:'' },
  { cat:'pb-rxns', cl:'c-qa-pb',
    f:'Pb²⁺ + SO₄²⁻ → ? conc H₂SO₄ → ? excess amm. acetate → ?', fs:'',
    b:'Pb²⁺ + SO₄²⁻ → PbSO₄↓\nConc H₂SO₄ → Pb(HSO₄)₂\nExcess CH₃COONH₄ → [Pb(CH₃COO)₄]²⁻', bs:'', n:'' },
  { cat:'pb-rxns', cl:'c-qa-pb',
    f:'Pb²⁺ + CrO₄²⁻ → ? Acid → ? Base → ?', fs:'',
    b:'Pb²⁺ + CrO₄²⁻ → PbCrO₄↓ (yellow)\nAcid → Pb²⁺ + Cr₂O₇²⁻ (orange-red)\nBase → [Pb(OH)₄]²⁻ + CrO₄²⁻ (yellow)', bs:'', n:'' },
  { cat:'pb-rxns', cl:'c-qa-pb',
    f:'Pb²⁺ + KI → ? excess KI → ?', fs:'',
    b:'Pb²⁺ + 2KI → PbI₂↓ (yellow)\nExcess KI → [PbI₄]²⁻', bs:'', n:'' },
  { cat:'pb-rxns', cl:'c-qa-pb',
    f:'Pb²⁺ + PO₄³⁻ → ?', fs:'',
    b:'3Pb²⁺ + 2PO₄³⁻ → Pb₃(PO₄)₂↓', bs:'', n:'' },
  { cat:'pb-rxns', cl:'c-qa-pb',
    f:'Pb²⁺ + 2CN⁻ → ? excess KCN → ?', fs:'',
    b:'Pb²⁺ + 2CN⁻ → Pb(CN)₂↓ (white)\nExcess KCN: No dissolution', bs:'', n:'' },

  // ── GROUP 1 — Ag⁺ ──
  { cat:'ag-rxns', cl:'c-qa-ag',
    f:'Ag⁺ + HCl → ? excess conc HCl/KCl → ?', fs:'',
    b:'Ag⁺ + HCl → AgCl↓ (white)\nAgCl + 2HCl(conc) → [AgCl₂]⁻', bs:'', n:'' },
  { cat:'ag-rxns', cl:'c-qa-ag',
    f:'AgCl/AgBr/AgI dissolution: dil NH₃ / conc NH₃ / KOH / Na₂S₂O₃?', fs:'',
    b:'AgCl: ✓dil NH₃  ✓conc NH₃  ✓KOH  ✓hypo\nAgBr: ✗dil NH₃  ✓conc NH₃  ✓KOH  ✓hypo\nAgI:  ✗dil NH₃  ✗conc NH₃  ✓KOH  ✓hypo',
    bs:'hypo = Na₂S₂O₃', n:'' },
  { cat:'ag-rxns', cl:'c-qa-ag',
    f:'Ag⁺ + H₂S → ? conc HNO₃ + Δ → ?', fs:'',
    b:'2Ag⁺ + H₂S → Ag₂S↓ (black)\nAg₂S + conc HNO₃ + Δ → Ag⁺ + S↓ (not gas)', bs:'', n:'' },
  { cat:'ag-rxns', cl:'c-qa-ag',
    f:'Ag⁺ + aq NH₃ → ? excess NH₃ → ?', fs:'',
    b:'2Ag⁺ + 2NH₃ + H₂O → Ag₂O↓ (brown)\nExcess NH₃: Ag₂O + 4NH₃ + H₂O → 2[Ag(NH₃)₂]⁺ + 2OH⁻', bs:'', n:'' },
  { cat:'ag-rxns', cl:'c-qa-ag',
    f:'Ag⁺ + aq NaOH → ? excess → ?', fs:'',
    b:'2Ag⁺ + 2NaOH → Ag₂O↓ + H₂O + 2Na⁺\nExcess NaOH: No dissolution', bs:'', n:'' },
  { cat:'ag-rxns', cl:'c-qa-ag',
    f:'Ag⁺ + KI → ?', fs:'',
    b:'Ag⁺ + KI → AgI↓ (yellow) + K⁺', bs:'', n:'' },
  { cat:'ag-rxns', cl:'c-qa-ag',
    f:'Ag⁺ + CrO₄²⁻ → ? aq NH₃ → ?', fs:'',
    b:'2Ag⁺ + CrO₄²⁻ → Ag₂CrO₄↓ (brick red)\nAg₂CrO₄ + 4NH₃ → 2[Ag(NH₃)₂]⁺ + CrO₄²⁻', bs:'', n:'' },
  { cat:'ag-rxns', cl:'c-qa-ag',
    f:'Ag⁺ + KCN → ? excess KCN → ?', fs:'',
    b:'Ag⁺ + KCN → AgCN↓ (white)\nAgCN + KCN → K[Ag(CN)₂]', bs:'', n:'' },
  { cat:'ag-rxns', cl:'c-qa-ag',
    f:'Ag⁺ + PO₄³⁻ → ?', fs:'',
    b:'3Ag⁺ + PO₄³⁻ → Ag₃PO₄↓ (yellow)', bs:'', n:'' },
  { cat:'ag-rxns', cl:'c-qa-ag',
    f:'Ag⁺ + AsO₄³⁻ → ?', fs:'',
    b:'3Ag⁺ + AsO₄³⁻ → Ag₃AsO₄↓ (brownish red)', bs:'', n:'' },
  { cat:'ag-rxns', cl:'c-qa-ag',
    f:'Ag⁺ + CO₃²⁻ → ? boiled → ?', fs:'',
    b:'2Ag⁺ + CO₃²⁻ → Ag₂CO₃↓\nBoiled: Ag₂CO₃ → Ag₂O (brown) + CO₂↑', bs:'', n:'' },
  { cat:'ag-rxns', cl:'c-qa-ag',
    f:'Ag⁺ + K₄[Fe(CN)₆] → ?', fs:'',
    b:'4Ag⁺ + K₄[Fe(CN)₆] → Ag₄[Fe(CN)₆]↓ (white ppt) + 4K⁺', bs:'', n:'' },

  // ── GROUP 1 — Hg₂²⁺ ──
  { cat:'hg2-rxns', cl:'c-qa-hg2',
    f:'Does Hg₂²⁺ exist as Hg⁺?', fs:'',
    b:'NO — Hg₂²⁺ is diamagnetic (paired electrons in Hg–Hg bond). Never Hg⁺.', bs:'', n:'' },
  { cat:'hg2-rxns', cl:'c-qa-hg2',
    f:'Hg₂²⁺ + HCl → ? NH₃ → ? aqua regia → ?', fs:'',
    b:'Hg₂²⁺ + 2HCl → Hg₂Cl₂↓ (white)\nNH₃: Hg₂Cl₂ → Hg↓(black) + Hg(NH₂)Cl(white) → overall black\nAqua regia: Hg₂Cl₂ → HgCl₂ + NO↑', bs:'', n:'' },
  { cat:'hg2-rxns', cl:'c-qa-hg2',
    f:'Hg₂²⁺ + H₂S → ?', fs:'',
    b:'Hg₂²⁺ + H₂S → HgS↓(black) + Hg↓(black)\nNa₂S → [HgSₓ]²⁻ (poly sulphides)', bs:'', n:'' },
  { cat:'hg2-rxns', cl:'c-qa-hg2',
    f:'Hg₂(NO₃)₂ + aq NH₃ → ?', fs:'',
    b:'Hg₂(NO₃)₂ + 2NH₃ → Hg↓(black) + HgOHg(NH₂)NO₃(white) + NH₄NO₃\nOverall: black ppt', bs:'', n:'' },
  { cat:'hg2-rxns', cl:'c-qa-hg2',
    f:'Hg₂²⁺ + aq NaOH → ? boil → ?', fs:'',
    b:'Hg₂²⁺ + 2NaOH → Hg₂O↓(black) + H₂O\nBoil: Hg₂O → HgO(yellow) + Hg↓', bs:'', n:'' },
  { cat:'hg2-rxns', cl:'c-qa-hg2',
    f:'Hg₂²⁺ + CrO₄²⁻ → ?', fs:'',
    b:'Hg₂²⁺ + CrO₄²⁻ → Hg₂CrO₄↓ (red ppt)', bs:'', n:'' },
  { cat:'hg2-rxns', cl:'c-qa-hg2',
    f:'Hg₂²⁺ + KI → ? boil → ? excess KI → ?', fs:'',
    b:'Hg₂²⁺ + 2KI → Hg₂I₂↓ (green ppt ★)\nBoil → Hg↓ + HgI₂ (red/scarlet ★)\nExcess KI: HgI₂ + 2KI → [HgI₄]²⁻ + Hg↓', bs:'', n:'' },
  { cat:'hg2-rxns', cl:'c-qa-hg2',
    f:'Hg₂²⁺ + KCN → ?', fs:'',
    b:'Hg₂²⁺ + 2KCN → Hg↓ + Hg(CN)₂ + 2K⁺\nGrey/black ppt', bs:'', n:'' },
  { cat:'hg2-rxns', cl:'c-qa-hg2',
    f:'Hg₂²⁺ + SnCl₂ → ?', fs:'',
    b:'Hg₂²⁺ + SnCl₂ → Hg↓(l) + SnCl₄', bs:'', n:'' },
  { cat:'hg2-rxns', cl:'c-qa-hg2',
    f:'Hg₂²⁺ + Cu/Al → ?', fs:'',
    b:'Hg₂²⁺ + Cu/Al → Hg↓(l) + Cu²⁺/Al³⁺', bs:'', n:'' },

  // ── GROUP 2A — Hg²⁺ ──
  { cat:'hg-rxns', cl:'c-qa-hg2',
    f:'★ Hg²⁺ + H₂S → ? aqua regia → ? Na₂S → ?', fs:'Group 2A',
    b:'Hg²⁺ + H₂S → HgS↓ (black)\nAqua regia: HgS + 3HCl + HNO₃ → HgCl₂ + S↓ + NO↑\nNa₂S: HgS + Na₂S → [HgS₂]²⁻', bs:'', n:'' },
  { cat:'hg-rxns', cl:'c-qa-hg2',
    f:'Hg(NO₃)₂ + aq NH₃ → ?', fs:'',
    b:'Hg(NO₃)₂ + 2NH₃ + H₂O → HgOHg(NH₂)NO₃↓ (white) + NH₄NO₃', bs:'', n:'' },
  { cat:'hg-rxns', cl:'c-qa-hg2',
    f:'Hg²⁺ + NaOH → ? excess → ?', fs:'',
    b:'Hg²⁺ + 2NaOH → HgO↓ (black ppt) + H₂O + 2Na⁺\nExcess NaOH: No dissolution', bs:'', n:'' },
  { cat:'hg-rxns', cl:'c-qa-hg2',
    f:'Hg²⁺ + KI → ? excess KI → ?', fs:'',
    b:'Hg²⁺ + 2KI → HgI₂↓ (red ppt)\nExcess KI: HgI₂ + 2KI → [HgI₄]²⁻', bs:'', n:'' },
  { cat:'hg-rxns', cl:'c-qa-hg2',
    f:'Hg²⁺ + SnCl₂ (RA) → ? more SnCl₂ → ?', fs:'Reducing agent test',
    b:'Hg²⁺ + SnCl₂ → Hg₂Cl₂↓ (white)\nMore SnCl₂: Hg₂Cl₂ + SnCl₂ → Hg↓ (grey/black) + SnCl₄', bs:'', n:'' },
  { cat:'hg-rxns', cl:'c-qa-hg2',
    f:'Hg²⁺ + Cu/Al → ?', fs:'Copper chip test',
    b:'Hg²⁺ + Cu/Al → Hg↓(l) + Cu²⁺/Al³⁺', bs:'', n:'' },
  { cat:'hg-rxns', cl:'c-qa-hg2',
    f:'★ Hg²⁺ + Co²⁺ + SCN⁻ → ?', fs:'',
    b:'Hg²⁺ + Co²⁺ + 4SCN⁻ → Co[Hg(SCN)₄]↓\nDeep blue ppt → polymeric chain-like solid\n(S coordinates to Hg; N coordinates to Co)', bs:'', n:'★ Important' },

  // ── GROUP 2A — Bi³⁺ ──
  { cat:'bi-rxns', cl:'c-qa-grp2a',
    f:'★ Bi³⁺ + H₂S → ? conc HNO₃/Δ → ? conc HCl → ?', fs:'',
    b:'2Bi³⁺ + 3H₂S → Bi₂S₃↓ (black; insol in YAS)\nConc HNO₃/Δ: Bi₂S₃ → Bi³⁺ + S↓ + NO↑\nConc HCl: Bi₂S₃ → BiCl₃(aq) + H₂S↑', bs:'', n:'' },
  { cat:'bi-rxns', cl:'c-qa-grp2a',
    f:'Bi³⁺ + aq NH₃ → ? excess → ?', fs:'',
    b:'Bi³⁺ + 3NH₃ + 3H₂O → Bi(OH)₃↓ (white) + 3NH₄⁺\nExcess NH₃: No dissolution', bs:'', n:'' },
  { cat:'bi-rxns', cl:'c-qa-grp2a',
    f:'★ Bi³⁺ + aq NaOH → ? Δ → ? H₂O₂ → ?', fs:'',
    b:'Bi³⁺ + 3NaOH → Bi(OH)₃↓\nΔ: Bi(OH)₃ → BiO⁺OH⁻ (yellowish white ppt)\nH₂O₂: BiO⁺OH⁻ → BiO₃⁻\nAq HCl: Bi(OH)₃ → BiCl₃', bs:'', n:'' },
  { cat:'bi-rxns', cl:'c-qa-grp2a',
    f:'★ Bi³⁺ + KI → ? excess KI → ? dilute → ? boil → ?', fs:'',
    b:'Bi³⁺ + 3KI → BiI₃↓ (black)\nExcess KI: BiI₃ + KI → [BiI₄]⁻ (orange soln)\nDilute: [BiI₄]⁻ → BiI₃↓ (black)\nBoil: [BiI₄]⁻ → BiO⁺I⁻↓ (orange ppt — bismuth oxyiodide)', bs:'', n:'' },
  { cat:'bi-rxns', cl:'c-qa-grp2a',
    f:'Bi³⁺ + [Sn(OH)₃]²⁻ → ?', fs:'Sodium stannite test',
    b:'2Bi³⁺ + 3[Sn(OH)₃]²⁻ → 2Bi↓ (black ppt) + 3[Sn(OH)₆]²⁻', bs:'', n:'' },
  { cat:'bi-rxns', cl:'c-qa-grp2a',
    f:'★ Bi(NO₃)₃ + large amount of water → ?', fs:'Hydrolysis',
    b:'Bi(NO₃)₃ + H₂O → BiO⁺NO₃⁻↓ + HNO₃\nWhite turbidity (bismuthyl nitrate)', bs:'', n:'' },
  { cat:'bi-rxns', cl:'c-qa-grp2a',
    f:'Bi³⁺ + pyrogallol (OH⁻ medium) → ?', fs:'',
    b:'Bi³⁺ + C₆H₃(OH)₃ + OH⁻ → Bi(C₆H₃O₃)↓ (yellow ppt)', bs:'', n:'' },

  // ── GROUP 2A — Cu²⁺ ──
  { cat:'cu-rxns', cl:'c-qa-grp2a',
    f:'★ Cu²⁺ + H₂S (HCl) → ? conc HNO₃/Δ → ? excess KCN → ? any OA → ?', fs:'',
    b:'Cu²⁺ + H₂S → CuS↓ (black; sol in YAS, NaOH, H₂SO₄, Na₂S)\nConc HNO₃/Δ: CuS → Cu²⁺ + S↓ + NO↑\nExcess KCN: CuS → [Cu(CN)₄]³⁻\nAny OA: CuS → CuSO₄', bs:'', n:'' },
  { cat:'cu-rxns', cl:'c-qa-grp2a',
    f:'Cu²⁺ + NH₃ + SO₄²⁻ → ? excess NH₃ → ?', fs:'',
    b:'Cu²⁺ + NH₃ + SO₄²⁻ → Cu(OH)₂·CuSO₄↓ (blue basic copper sulphate)\nExcess NH₃ → [Cu(NH₃)₄]²⁺ + SO₄²⁻', bs:'', n:'' },
  { cat:'cu-rxns', cl:'c-qa-grp2a',
    f:'Cu²⁺ + NaOH → ? Δ → ?', fs:'',
    b:'Cu²⁺ + 2NaOH → Cu(OH)₂↓ (blue)\nΔ: Cu(OH)₂ → CuO (black) + H₂O', bs:'', n:'' },
  { cat:'cu-rxns', cl:'c-qa-grp2a',
    f:'Cu²⁺ + KI → ?', fs:'Iodometric titration',
    b:'2Cu²⁺ + 4KI → 2CuI↓ (white ppt) + I₃⁻ + 3K⁺\nI₃⁻ titrated with Na₂S₂O₃', bs:'', n:'' },
  { cat:'cu-rxns', cl:'c-qa-grp2a',
    f:'★ Cu²⁺ + KCN → ? quick decomp → ?', fs:'',
    b:'Cu²⁺ + 2KCN → Cu(CN)₂↓ (yellow, unstable)\nQuick decomp: Cu(CN)₂ → CuCN↓ + (CN)₂↑ (poisonous — liberates halogen-like gas)', bs:'', n:'' },
  { cat:'cu-rxns', cl:'c-qa-grp2a',
    f:'Cu²⁺ + SCN⁻ → ? slow decomp → ?', fs:'',
    b:'Cu²⁺ + 2SCN⁻ → Cu(SCN)₂↓ (black, unstable)\nSlow decomp: Cu(SCN)₂ → CuSCN (white) + (SCN)₂↑ (thiocyanogen gas)', bs:'', n:'' },
  { cat:'cu-rxns', cl:'c-qa-grp2a',
    f:'Cu²⁺ + K₄[Fe(CN)₆] → ?', fs:'',
    b:'2Cu²⁺ + [Fe(CN)₆]⁴⁻ → Cu₂[Fe(CN)₆]↓ (chocolate brown ppt)', bs:'', n:'' },
  { cat:'cu-rxns', cl:'c-qa-grp2a',
    f:'Cu²⁺ + K₃[Fe(CN)₆] → ?', fs:'',
    b:'3Cu²⁺ + 2[Fe(CN)₆]³⁻ → Cu₃[Fe(CN)₆]₂↓ (green ppt)', bs:'', n:'' },
  { cat:'cu-rxns', cl:'c-qa-grp2a',
    f:'Distinction: Cu²⁺ vs Cd²⁺ using excess KCN + H₂S', fs:'',
    b:'Cu²⁺ + excess KCN → [Cu(CN)₄]³⁻ + H₂S → No ppt\nCd²⁺ + excess KCN → [Cd(CN)₄]²⁻ + H₂S → CdS↓ (yellow)\nCd²⁺ gives yellow ppt; Cu²⁺ does not', bs:'', n:'' },

  // ── GROUP 2A — Cd²⁺ ──
  { cat:'cd-rxns', cl:'c-qa-grp2a',
    f:'Cd²⁺ + H₂S → ? conc HNO₃ → ?', fs:'Fixed OS (+2)',
    b:'Cd²⁺ + H₂S → CdS↓ (yellow ppt)\nCdS + conc HNO₃ + boil → Cd²⁺ + S↓ + NO↑', bs:'', n:'' },
  { cat:'cd-rxns', cl:'c-qa-grp2a',
    f:'Cd²⁺ + aq NH₃ → ? excess → ?', fs:'',
    b:'Cd²⁺ + 2NH₃ + 2H₂O → Cd(OH)₂↓ (white)\nExcess NH₃: Cd(OH)₂ + 4NH₃ → [Cd(NH₃)₄]²⁺ + 2OH⁻', bs:'', n:'' },
  { cat:'cd-rxns', cl:'c-qa-grp2a',
    f:'Cd²⁺ + KCN → ? excess → ?', fs:'',
    b:'Cd²⁺ + 2KCN → Cd(CN)₂↓ (white ppt)\nExcess KCN: Cd(CN)₂ + 2KCN → K₂[Cd(CN)₄]', bs:'', n:'' },
  { cat:'cd-rxns', cl:'c-qa-grp2a',
    f:'Cd²⁺ + KI → ?', fs:'',
    b:'Cd²⁺ + KI → No reaction\n(CdS₂ is water soluble)', bs:'', n:'' },

  // ── GROUP 2B — As³⁺ ──
  { cat:'as-rxns', cl:'c-qa-grp2b',
    f:'As³⁺ + H₂S → ? YAS → ? HCl → ? conc HNO₃ → ?', fs:'Group 2B — only As³⁺ in JEE',
    b:'2As³⁺ + 3H₂S → As₂S₃↓ (yellow)\nYAS [(NH₄)₂Sₓ]: As₂S₃ → (NH₄)₃AsS₄ + S↓\nHCl: (NH₄)₃AsS₄ → As₂S₅ + H₂S↑ + NH₄Cl\nConc HNO₃: As₂S₅ → H₃AsO₄ + S↓ + NO↑',
    bs:'2B soluble in YAS — distinction from 2A', n:'' },
  { cat:'as-rxns', cl:'c-qa-grp2b',
    f:'As³⁺ + (NH₄)₃MoO₄ → ?', fs:'Molybdate test',
    b:'As³⁺ + (NH₄)₃MoO₄ → (NH₄)₃[As(Mo₃O₁₀)₄]↓ (yellow ppt)\nAmmonium arsenomolybdate', bs:'', n:'' },

  // ── GROUP 3 — Al³⁺ ──
  { cat:'al-rxns', cl:'c-qa-grp3',
    f:'★ Al³⁺ + NH₄OH (NH₄Cl) → ? excess NH₃ → ?', fs:'',
    b:'Al³⁺ + 3NH₄OH → Al(OH)₃↓ (gelatinous white) + 3NH₄⁺\nExcess NH₃: No dissolution\n(Distinction: Zn(OH)₂ dissolves, Al(OH)₃ does not)',
    bs:'', n:'★ Lake test: Al³⁺ + blue litmus → red (acidic due to cationic hydrolysis). Add NH₄OH dropwise → Al(OH)₃ adsorbs blue litmus → blue lake floating in clear soln' },
  { cat:'al-rxns', cl:'c-qa-grp3',
    f:'Al³⁺ + aq NaOH → ? excess → ? dropwise HCl → ?', fs:'',
    b:'Al³⁺ + 3NaOH → Al(OH)₃↓\nExcess NaOH: Al(OH)₃ + NaOH → [Al(OH)₄]⁻ or NaAlO₂\nDropwise HCl: [Al(OH)₄]⁻ → Al(OH)₃↓; excess HCl → AlCl₃', bs:'', n:'' },
  { cat:'al-rxns', cl:'c-qa-grp3',
    f:'[Al(OH)₄]⁻ + NH₄Cl → ?', fs:'',
    b:'[Al(OH)₄]⁻ + NH₄Cl → Al(OH)₃↓ (white ppt) + NH₃ + H₂O + Cl⁻', bs:'', n:'' },
  { cat:'al-rxns', cl:'c-qa-grp3',
    f:'★ Al³⁺ + (NH₄)₂S → ?', fs:'',
    b:'2Al³⁺ + 3(NH₄)₂S + 6H₂O → 2Al(OH)₃↓ (white) + 3H₂S↑ + 6NH₄⁺\n(Al₂S₃ cannot exist in aqueous soln — undergoes hydrolysis)', bs:'', n:'' },
  { cat:'al-rxns', cl:'c-qa-grp3',
    f:'Al³⁺ + HPO₄²⁻ → ?', fs:'',
    b:'Al³⁺ + HPO₄²⁻ → AlPO₄↓ (yellow-white ppt)', bs:'', n:'' },
  { cat:'al-rxns', cl:'c-qa-grp3',
    f:'★ Al³⁺ + CH₃COO⁻ → ? soln boiled → ?', fs:'',
    b:'Al³⁺ + CH₃COO⁻ → initially no change\nBoiled: Al³⁺ + 3CH₃COO⁻ + 2H₂O → Al(OH)₂(CH₃COO)↓ (white) + 2CH₃COOH', bs:'', n:'' },
  { cat:'al-rxns', cl:'c-qa-grp3',
    f:'★ Cobalt nitrate test for Al³⁺ vs Zn²⁺', fs:'',
    b:'Al³⁺: Al(OH)₃ + Co(NO₃)₂ →Δ→ Al₂O₃·CoO (Thenard\'s blue)\nZn²⁺: Zn(OH)₂ + Co(NO₃)₂ →Δ→ ZnO·CoO (Rinman\'s green)', bs:'', n:'' },

  // ── GROUP 3 — Cr³⁺ ──
  { cat:'cr-rxns', cl:'c-qa-grp3',
    f:'Cr³⁺ + NH₄OH (NH₄Cl) → ? excess NH₃ → ?', fs:'',
    b:'Cr³⁺ + 3NH₄OH → Cr(OH)₃↓ (dirty green) + 3NH₄⁺\nExcess NH₃: Cr(OH)₃ + 6NH₃ → [Cr(NH₃)₆]³⁺ (pink-white soln)', bs:'', n:'' },
  { cat:'cr-rxns', cl:'c-qa-grp3',
    f:'★ Cr³⁺ + NaOH → ? excess → ? H₂O₂ → ?', fs:'',
    b:'Cr³⁺ + 3NaOH → Cr(OH)₃↓\nExcess NaOH: Cr(OH)₃ + NaOH → [Cr(OH)₄]⁻\nH₂O₂: 2[Cr(OH)₄]⁻ + 3H₂O₂ → Na₂CrO₄ (yellow) + 4H₂O', bs:'', n:'' },
  { cat:'cr-rxns', cl:'c-qa-grp3',
    f:'Na₂CrO₄ (yellow) + Ag⁺/Ba²⁺/Pb²⁺ → ?', fs:'',
    b:'2Ag⁺ + CrO₄²⁻ → Ag₂CrO₄↓ (red)\nBa²⁺ + CrO₄²⁻ → BaCrO₄↓ (yellow)\nPb²⁺ + CrO₄²⁻ → PbCrO₄↓ (yellow)', bs:'', n:'' },
  { cat:'cr-rxns', cl:'c-qa-grp3',
    f:'Cr(OH)₃ + Na₂CO₃ + KNO₃ → Δ fusion → ?', fs:'',
    b:'Cr(OH)₃ + Na₂CO₃ + KNO₃ →Δ→ Na₂CrO₄ + KNO₂ + CO₂↑ + H₂O↑', bs:'', n:'' },
  { cat:'cr-rxns', cl:'c-qa-grp3',
    f:'Cr(OH)₃ → CrO₄²⁻: 3 oxidation methods?', fs:'',
    b:'1) Cr(OH)₃ + NaOH + H₂O₂ → CrO₄²⁻\n2) Cr(OH)₃ + NaOH + Br₂ → CrO₄²⁻\n3) Cr(OH)₃ + NaOBr → CrO₄²⁻', bs:'', n:'' },
  { cat:'cr-rxns', cl:'c-qa-grp3',
    f:'Cr₂O₇²⁻ + H₂SO₄ + H₂O₂ → ?', fs:'',
    b:'Cr₂O₇²⁻ + H₂SO₄ + H₂O₂ → CrO₅ (blue soln; stable in amyl alcohol)\nCrO₅ has butterfly structure (5 oxygens around Cr)', bs:'', n:'' },

  // ── GROUP 3 — Fe²⁺/Fe³⁺ ──
  { cat:'fe-rxns', cl:'c-qa-grp3',
    f:'Fe²⁺ vs Fe³⁺ + NaOH → ?', fs:'VIMP',
    b:'Fe²⁺ + 2NaOH → Fe(OH)₂↓ (white) → atm O₂/Δ → Fe(OH)₃ (reddish brown)\nFe³⁺ + 3NaOH → Fe(OH)₃↓ (reddish brown)', bs:'', n:'' },
  { cat:'fe-rxns', cl:'c-qa-grp3',
    f:'Fe²⁺ vs Fe³⁺ + aq NH₃ → ?', fs:'',
    b:'Fe²⁺ + 2NH₃ + 2H₂O → Fe(OH)₂↓; dissolves in NH₄Cl → Fe²⁺\nFe³⁺ + 3NH₃ + 3H₂O → Fe(OH)₃↓; excess NH₃: No dissolution', bs:'', n:'' },
  { cat:'fe-rxns', cl:'c-qa-grp3',
    f:'Fe²⁺ vs Fe³⁺ + H₂S (acidic/basic/neutral) → ?', fs:'',
    b:'Fe²⁺ acidic: No ppt; basic: Fe²⁺ + S²⁻ → FeS↓ (black)\nFe³⁺ acidic/neutral: Fe³⁺ + H₂S → Fe²⁺ + S↓; basic: Fe³⁺ + S²⁻ → Fe₂S₃ (black)\n(NH₄)₂S: Fe²⁺ → FeS; Fe³⁺ neutral → FeS+S; basic → Fe₂S₃', bs:'', n:'' },
  { cat:'fe-rxns', cl:'c-qa-grp3',
    f:'Fe²⁺ vs Fe³⁺ + KCN → ?', fs:'',
    b:'Fe²⁺ + aq KCN → Fe(CN)₂↓ (pale yellow); excess KCN → K₄[Fe(CN)₆] (pot ferrocyanide)\nFe³⁺ + KCN → Fe(CN)₃ (reddish brown); excess KCN → K₃[Fe(CN)₆] (pot ferricyanide)', bs:'', n:'' },
  { cat:'fe-rxns', cl:'c-qa-grp3',
    f:'Fe²⁺ vs Fe³⁺ + K₄[Fe(CN)₆] → ?', fs:'',
    b:'Fe²⁺ + [Fe(CN)₆]⁴⁻ → K₂Fe[Fe(CN)₆]↓ (white) → air → Prussian blue Fe₄[Fe(CN)₆]₃\nFe³⁺ + K₄[Fe(CN)₆] → Fe₄[Fe(CN)₆]₃ (Prussian blue); excess → KFe[Fe(CN)₆] (soluble Prussian blue)\n+ NaOH → Fe(OH)₃↓; + H₂C₂O₄ → [Fe(C₂O₄)₃]³⁻ (blue soln)', bs:'', n:'' },
  { cat:'fe-rxns', cl:'c-qa-grp3',
    f:'Fe²⁺ vs Fe³⁺ + K₃[Fe(CN)₆] → ?', fs:'',
    b:'Fe²⁺ + K₃[Fe(CN)₆] → Fe₃[Fe(CN)₆]₂ (Turnbull\'s blue) → Fe₄[Fe(CN)₆]₃ (Prussian blue)\nFe³⁺ + [Fe(CN)₆]³⁻ → Fe[Fe(CN)₆] (brown soln); SnO₂/H₂O → Fe₄[Fe(CN)₆] (Prussian blue)', bs:'', n:'' },
  { cat:'fe-rxns', cl:'c-qa-grp3',
    f:'Fe²⁺ vs Fe³⁺ + SCN⁻ → ?', fs:'',
    b:'Fe²⁺ + SCN⁻ → No rxn\nFe³⁺ + 3SCN⁻ → Fe(SCN)₃ (blood red soln)\nFe(SCN)₃ + excess F⁻ → [FeF₆]³⁻ (colourless)\nFe(SCN)₃ + Hg²⁺ → Fe³⁺ + Hg(SCN)₂ (colourless)', bs:'', n:'' },
  { cat:'fe-rxns', cl:'c-qa-grp3',
    f:'Fe²⁺ + dmg (NH₄OH) → ? | Fe³⁺ + dmg → ? | + CH₃COO⁻ → ?', fs:'dmg = dimethylglyoxime',
    b:'Fe²⁺ + dmg + NH₄OH → Fe(dmg)₂\nFe³⁺ + dmg → No rxn\nFe²⁺ + CH₃COO⁻ → No rxn\nFe³⁺ + CH₃COO⁻ → [Fe(OH)₂(CH₃COO)₄]⁺ (red soln)',
    bs:'', n:'Note: Co²⁺ + dmg → brown soln; Ni²⁺ + dmg → rose red ppt ★; Bi³⁺ + dmg + NaOH → yellow ppt' },

  // ── GROUP 4 — Co²⁺ ──
  { cat:'co-rxns', cl:'c-qa-grp4',
    f:'Co²⁺ + H₂S (NH₄OH) → ?', fs:'Co²⁺ exists as pink [Co(H₂O)₆]²⁺',
    b:'Co²⁺ + H₂S + NH₄OH → CoS↓ (black ppt)\nInsol in dil HCl, CH₃COOH; sol in conc HNO₃, aqua regia',
    bs:'', n:'In aq soln Co²⁺ is more stable than Co³⁺; but in complex salt form, Co³⁺ complexes are highly stable' },
  { cat:'co-rxns', cl:'c-qa-grp4',
    f:'Co²⁺ + aq NaOH → ? excess/warm → ? O₂/OA → ?', fs:'',
    b:'Co²⁺ + NaOH → Co(OH)(NO₃)↓ (blue ppt)\nExcess NaOH/warm → Co(OH)₂↓ (pink ppt)\nO₂/OA: Co(OH)₂ → Co(OH)₃ (brownish black)', bs:'', n:'' },
  { cat:'co-rxns', cl:'c-qa-grp4',
    f:'★ Co²⁺ + excess KCl → ?', fs:'',
    b:'Co²⁺ + 4KCl(excess) → K₂[CoCl₄]²⁻ (blue soln)', bs:'', n:'' },
  { cat:'co-rxns', cl:'c-qa-grp4',
    f:'Co²⁺ + aq NH₃ → ? excess → ? bubbling air → ?', fs:'',
    b:'Co(NO₃)₂ + NH₃ → Co(OH)NO₃↓\nExcess NH₃ → [Co(NH₃)₆]²⁺\nBubbling air: [Co(NH₃)₆]²⁺ → [Co(NH₃)₆]³⁺', bs:'', n:'' },
  { cat:'co-rxns', cl:'c-qa-grp4',
    f:'Co²⁺ + KCN → ? excess KCN → ? O₂ → ?', fs:'',
    b:'Co²⁺ + 2KCN → Co(CN)₂↓ (buff/light pink ppt)\nExcess KCN → [Co(CN)₆]⁵⁻\nO₂: [Co(CN)₆]⁵⁻ → [Co(CN)₆]³⁻', bs:'', n:'' },
  { cat:'co-rxns', cl:'c-qa-grp4',
    f:'Co²⁺ + KNO₂ (CH₃COOH medium) → ?', fs:'',
    b:'Co²⁺ + 3KNO₂ + CH₃COOH → K₃[Co(NO₂)₆]↓ (yellow ppt)', bs:'', n:'' },
  { cat:'co-rxns', cl:'c-qa-grp4',
    f:'★ Co²⁺ + NH₄SCN (in ether/amyl alcohol) → ?', fs:'',
    b:'Co²⁺ + 4NH₄SCN → [Co(SCN)₄]²⁻ (blue soln in ether/amyl alcohol)', bs:'', n:'' },
  { cat:'co-rxns', cl:'c-qa-grp4',
    f:'★ Co²⁺ + NaHCO₃ → ? excess → ?', fs:'Sodium bicarbonate & bromine water test',
    b:'Co²⁺ + NaHCO₃ → Co(HCO₃)₂\nExcess NaHCO₃ → Na₄[Co(CO₃)₃] (+2)\n→ Na₃[Co(CO₃)₃] (+3, apple green)', bs:'', n:'' },

  // ── GROUP 4 — Ni²⁺ ──
  { cat:'ni-rxns', cl:'c-qa-grp4',
    f:'Ni²⁺ + H₂S (NH₄OH) → ?', fs:'',
    b:'Ni²⁺ + H₂S + NH₄OH → NiS↓ (black ppt)\nInsol in dil HCl, CH₃COOH; sol in conc HNO₃, aqua regia', bs:'', n:'' },
  { cat:'ni-rxns', cl:'c-qa-grp4',
    f:'Ni²⁺ + aq NaOH → ? NaClO (OA) → ?', fs:'',
    b:'Ni²⁺ + 2NaOH → Ni(OH)₂↓ (green ppt)\nNaClO (sod. hypochlorite): Ni(OH)₂ → Ni(OH)₃↓ (black ppt)', bs:'', n:'' },
  { cat:'ni-rxns', cl:'c-qa-grp4',
    f:'Ni²⁺ + aq NH₃ → ? excess → ?', fs:'',
    b:'Ni²⁺ + 2NH₃ + 2H₂O → Ni(OH)₂↓\nExcess NH₃: Ni(OH)₂ + 6NH₃ → [Ni(NH₃)₆]²⁺ + 2OH⁻', bs:'', n:'' },
  { cat:'ni-rxns', cl:'c-qa-grp4',
    f:'Ni²⁺ + KCN → ? excess → ? Br₂/NaOH → ?', fs:'',
    b:'Ni²⁺ + 2KCN → Ni(CN)₂↓ (green)\nExcess KCN → K₂[Ni(CN)₄]²⁻\nBr₂/NaOH: [Ni(CN)₄]²⁻ → Ni(OH)₄↓ (black)', bs:'', n:'' },
  { cat:'ni-rxns', cl:'c-qa-grp4',
    f:'★ Ni²⁺ + dmgH₂ → ?', fs:'dmg = dimethylglyoxime',
    b:'Ni²⁺ + 2dmgH₂ → [Ni(dmgH)₂]↓ (rose red ppt)\nSquare planar; intramolecular H-bonding', bs:'', n:'★ Most important test for Ni²⁺' },
  { cat:'ni-rxns', cl:'c-qa-grp4',
    f:'Ni²⁺ + NaHCO₃ → ? Br₂ water → ?', fs:'',
    b:'Ni²⁺ + NaHCO₃ → Ni(HCO₃)₂\nBr₂ water: Ni(HCO₃)₂ → Ni₂O₃', bs:'', n:'' },

  // ── GROUP 4 — Mn²⁺ ──
  { cat:'mn-rxns', cl:'c-qa-grp4',
    f:'Mn²⁺ + H₂S (NH₄OH) → ?', fs:'',
    b:'Mn²⁺ + H₂S + NH₄OH → MnS↓ (light pink)\nSol in dil HCl, CH₃COOH; sol in conc HNO₃/aqua regia',
    bs:'Solubility: NiS,CoS (black) — insol dil HCl; MnS — sol dil HCl; ZnS — sol dil HCl', n:'' },
  { cat:'mn-rxns', cl:'c-qa-grp4',
    f:'Mn²⁺ + aq NaOH → ? atm O₂ → ?', fs:'',
    b:'Mn²⁺ + 2NaOH → Mn(OH)₂↓ (white)\nAtm O₂: Mn(OH)₂ → MnO₂·H₂O (brown-black ppt)', bs:'', n:'' },
  { cat:'mn-rxns', cl:'c-qa-grp4',
    f:'Mn²⁺ + aq NH₃ ⇌ ?', fs:'',
    b:'Mn²⁺ + 2NH₃ + 2H₂O ⇌ Mn(OH)₂↓ + 2NH₄⁺\nPartial ppt only (equilibrium)', bs:'', n:'' },
  { cat:'mn-rxns', cl:'c-qa-grp4',
    f:'Mn²⁺ + Na₂HPO₄ + NH₄Cl → ?', fs:'',
    b:'Mn²⁺ + Na₂HPO₄ + NH₄Cl → Mn(NH₄)(PO₄)·7H₂O↓ (pink)', bs:'', n:'' },
  { cat:'mn-rxns', cl:'c-qa-grp4',
    f:'★ Mn²⁺ + HNO₃ + PbO₂ (conc H₂SO₄) → ?', fs:'Strong OA: also S₂O₈²⁻ or BiO₂⁻',
    b:'Mn²⁺ + conc HNO₃ + PbO₂ (conc H₂SO₄) → MnO₄⁻ (purple soln)\nAlso: S₂O₈²⁻ or BiO₂⁻ oxidise Mn²⁺ → MnO₄⁻', bs:'', n:'★ Important oxidation test for Mn²⁺' },

  // ── GROUP 4 — Zn²⁺ ──
  { cat:'zn-rxns', cl:'c-qa-grp4',
    f:'Zn²⁺ + H₂S (NH₄OH) → ?', fs:'',
    b:'Zn²⁺ + H₂S + NH₄OH → ZnS↓ (dirty white ppt)\nSol in HCl, HNO₃; insol in CH₃COOH', bs:'', n:'' },
  { cat:'zn-rxns', cl:'c-qa-grp4',
    f:'Zn²⁺ + aq NaOH → ? excess → ?', fs:'',
    b:'Zn²⁺ + 2NaOH → Zn(OH)₂↓ (gelatinous white)\nExcess NaOH: Zn(OH)₂ + 2NaOH → Na₂ZnO₂ + 2H₂O', bs:'', n:'' },
  { cat:'zn-rxns', cl:'c-qa-grp4',
    f:'★ Zn²⁺ + aq NH₃ → ? excess → ?', fs:'',
    b:'Zn²⁺ + 2NH₃ + 2H₂O → Zn(OH)₂↓ (white)\nExcess NH₃: Zn(OH)₂ + 4NH₃ → [Zn(NH₃)₄]²⁺ + 2OH⁻\n(Al(OH)₃ does NOT dissolve in excess NH₃ — key distinction)', bs:'', n:'' },
  { cat:'zn-rxns', cl:'c-qa-grp4',
    f:'Zn²⁺ + Na₂HPO₄ → ? aq NH₃ → ?', fs:'',
    b:'3Zn²⁺ + 2Na₂HPO₄ → Zn₃(PO₄)₂↓ (white ppt)\nAq NH₃: Zn₃(PO₄)₂ + NH₃ → [Zn(NH₃)₄]²⁺ + PO₄³⁻', bs:'', n:'' },
  { cat:'zn-rxns', cl:'c-qa-grp4',
    f:'Zn²⁺ + K₄[Fe(CN)₆] → ? excess → ?', fs:'',
    b:'2Zn²⁺ + K₄[Fe(CN)₆] → Zn₂[Fe(CN)₆]↓ (bluish white ppt)\nExcess K₄Fe(CN)₆ → K₂Zn₃[Fe(CN)₆]₂↓ (bluish white)\nNaOH → Na₂ZnO₂', bs:'', n:'' },
  { cat:'zn-rxns', cl:'c-qa-grp4',
    f:'Zn²⁺ + CuSO₄ + (NH₄)₂[Hg(SCN)₄] → ?', fs:'',
    b:'Zn²⁺ + CuSO₄ + (NH₄)₂[Hg(SCN)₄] → Cu[Hg(SCN)₄]↓ (violet ppt) + Zn[Hg(SCN)₄]↓ (white)', bs:'', n:'' },

  // ── GROUP 5 — Ba²⁺ ──
  { cat:'ba-rxns', cl:'c-qa-grp5',
    f:'Ba²⁺ + (NH₄)₂CO₃ → ?', fs:'',
    b:'Ba²⁺ + (NH₄)₂CO₃ → BaCO₃↓ (white; sol in HCl, CH₃COOH)', bs:'', n:'' },
  { cat:'ba-rxns', cl:'c-qa-grp5',
    f:'★ Ba²⁺ + K₂Cr₂O₇ → ? distinction from Sr/Ca?', fs:'',
    b:'Ba²⁺ + K₂Cr₂O₇ → BaCrO₄↓ (yellow ppt)\nBaCrO₄ insol in CH₃COOH; SrCrO₄ and CaCrO₄ sol in CH₃COOH\nKsp order: BaCrO₄ << SrCrO₄ < CaCrO₄', bs:'', n:'' },

  // ── GROUP 5 — Sr²⁺ ──
  { cat:'sr-rxns', cl:'c-qa-grp5',
    f:'Sr²⁺ + (NH₄)₂CO₃ → ?', fs:'',
    b:'Sr²⁺ + (NH₄)₂CO₃ → SrCO₃↓ (white; sol in CH₃COOH, HCl)', bs:'', n:'' },
  { cat:'sr-rxns', cl:'c-qa-grp5',
    f:'Sr²⁺ + K₂CrO₄ (conc) → ? HCl → ?', fs:'',
    b:'Sr²⁺ + K₂CrO₄(conc) → SrCrO₄↓\nHCl: SrCrO₄ → Sr²⁺ + Cr₂O₇²⁻', bs:'', n:'' },

  // ── GROUP 5 — Ca²⁺ ──
  { cat:'ca-rxns', cl:'c-qa-grp5',
    f:'Ca²⁺ + (NH₄)₂CO₃ → ? HCl → ?', fs:'',
    b:'Ca²⁺ + (NH₄)₂CO₃ → CaCO₃↓ (white; sol in HCl, CH₃COOH)\nHCl: CaCO₃ + 2HCl → CaCl₂ + CO₂↑ + H₂O', bs:'', n:'' },
  { cat:'ca-rxns', cl:'c-qa-grp5',
    f:'★ Ca²⁺ + (NH₄)₂C₂O₄ → ?', fs:'Most insoluble oxalate test',
    b:'Ca²⁺ + (NH₄)₂C₂O₄ → CaC₂O₄↓ (white; most insol oxalate ppt)\nSolubility of sulphates: CaSO₄ > SrSO₄ > BaSO₄', bs:'', n:'' },
  { cat:'ca-rxns', cl:'c-qa-grp5',
    f:'Ca²⁺ + (NH₄)₂SO₄ → ?', fs:'',
    b:'Ca²⁺ + (NH₄)₂SO₄ → (NH₄)₂[Ca(SO₄)₂] (soluble complex)', bs:'', n:'' },
  { cat:'ca-rxns', cl:'c-qa-grp5',
    f:'★ Ca²⁺ + K₄[Fe(CN)₆] → ? (Ba²⁺ and Sr²⁺ comparison)', fs:'',
    b:'Ca²⁺ + K₄[Fe(CN)₆] → K₂Ca[Fe(CN)₆]↓ (white ppt)\nBa²⁺ and Sr²⁺ do NOT give this reaction', bs:'', n:'★ Key distinction' },

  // ── GROUP 6 — Mg²⁺ ──
  { cat:'mg-rxns', cl:'c-qa-grp6',
    f:'Mg²⁺ + Na₂HPO₄ (NH₄OH) → ?', fs:'',
    b:'Mg²⁺ + Na₂HPO₄ + NH₄OH → Mg(NH₄)PO₄↓ (white ppt)', bs:'', n:'' },
  { cat:'mg-rxns', cl:'c-qa-grp6',
    f:'Mg²⁺ + aq NH₃ → ? ammonium salts → ?', fs:'',
    b:'Mg²⁺ + 2NH₃ + 2H₂O → Mg(OH)₂↓ (white ppt)\nAmmonium salts: Mg(OH)₂ + 2NH₄⁺ → Mg²⁺ + 2NH₃/NH₄OH (ppt dissolves)', bs:'', n:'' },
  { cat:'mg-rxns', cl:'c-qa-grp6',
    f:'Mg²⁺ + (NH₄)₂CO₃ → ?', fs:'',
    b:'5Mg²⁺ + (NH₄)₂CO₃ + H₂O → 4MgCO₃·Mg(OH)₂·5H₂O↓\nBasic magnesium carbonate (white ppt)', bs:'', n:'' },
  { cat:'mg-rxns', cl:'c-qa-grp6',
    f:'★ Mg²⁺ + Magneson-I (red dye) + NaOH → ?', fs:'',
    b:'Mg²⁺ + Magneson-I + NaOH → Blue lake / blue ppt\n(For Ba²⁺ and Ca²⁺: only intensifies colour, does not change it)', bs:'', n:'' },
  { cat:'mg-rxns', cl:'c-qa-grp6',
    f:'★ Mg²⁺ + Titan yellow (yellow dye) + NaOH → ?', fs:'',
    b:'Mg²⁺ + Titan yellow + NaOH → Red colouration / red ppt\n(For Ba²⁺ and Ca²⁺: only intensifies colour, does not change it)', bs:'', n:'' },
];
